/* =============== FASE 1 · Ayudas: cobertura en atribución, ajustes por país, precarga en formularios, flujo de órdenes =============== */
function derivFix(){const d=dp(),Q=qcps();
 DERIV_ORDERS.forEach(o=>{if(!d.inst.includes(o.inst))o.inst='Forward';o.sub=o.inst==='Swap'?MM_RATES[2].code:d.par;
  if(o.id==='DV-0007'){o.quotes=seedQuotes(Object.assign({},o,{cp:Q[0]}),false).slice(0,2)}
  else{o.quotes=seedQuotes(o,!!o.just||o.id==='DV-0008');const q=o.quotes.find(x=>x.cp===o.cp);o.precio=q?q.precio:null}});
 DERIV_POS.forEach(p=>{const o=DERIV_ORDERS.find(x=>x.id===p.ord);if(o){p.inst=o.inst;p.sub=o.sub;p.delta=o.inst==='Opción'?0.46:null;p.vega=o.inst==='Opción'?132000:null}});
 DERIV_EXPO.forEach(e=>{if(e.sub!==MM_RATES[2].code)e.sub=d.par});
 DERIV_EVID.forEach(ev=>{const o=DERIV_ORDERS.find(x=>x.id===ev.ord);if(!o||ev.ver>1)return;const ind=derivIndicative(o),best=rankQ(o.quotes)[0],q=o.quotes.find(x=>x.cp===o.cp);Object.assign(ev,{cp:o.cp,precio:q.precio,hora:q.hora,indicativo:ind.valor,unidad:ind.unidad,mejor:best.cp,quotes:o.quotes.map(x=>Object.assign({},x))})});
}
/* Efecto de la cobertura en la atribución de retorno (retorno del activo, costo o ganancia por puntos forward, retorno neto cubierto). SUPUESTO: cifras ilustrativas. */
/* SUPUESTO (cifras ilustrativas): peso de la exposición cubierta, retorno del activo y costo o ganancia por puntos forward. */
function hedgeEffect(port,per){if(!hasDeriv(port))return null;
 const r=rng(hash(port+'hdg'+per)),k=PERIODS[per].k,cob=DERIV_POS.filter(p=>p.port===port&&p.prop==='Cobertura').reduce((a,p)=>a+p.noc,0),sv0=SENS.find(x=>x.port===port),val=sv0?sv0.val:2e10,w=Math.min(0.6,cob/val*3);
 const asset=(0.006+r()*0.008)*k,cost=(0.0004+r()*0.0016)*k*(r()>0.35?-1:1);return {asset,cost,cubierto:asset+cost,w,net:w*cost}}
function hedgeCard(h){const ef=v=>valC(v,bps(v));return '<div class="mk-card mk-mt"><h3 style="margin:0 0 8px;font-size:14px">Efecto de la cobertura</h3><div class="mk-tablewrap"><table class="mk-table"><thead><tr><th>Concepto</th><th>Valor</th></tr></thead><tbody><tr><td>Retorno del activo expuesto (sin cubrir)</td><td>'+pcs(h.asset)+'</td></tr><tr><td>Costo o ganancia de la cobertura (puntos forward)</td><td>'+ef(h.cost)+'</td></tr><tr><td>Retorno neto cubierto</td><td>'+pcs(h.cubierto)+'</td></tr><tr><td>Peso de la exposición cubierta en el portafolio</td><td>'+pct(h.w,1)+'</td></tr><tr><td><b>Efecto en el retorno del portafolio</b></td><td><b>'+ef(h.net)+'</b></td></tr></tbody></table></div><p class="mk-help mk-mt">Efecto de cobertura = peso de la exposición cubierta × costo o ganancia por puntos forward. Cifras ilustrativas.</p></div>'}
/* Precarga en formularios: emisor, moneda y valor indicativo vienen de New Inversiones y no se digitan. */
const preFld=(l,n)=>fld(l,'<input class="mk-input" name="'+n+'" readonly placeholder="Se completa al elegir el instrumento">',{name:n,tip:'Dato precargado desde New Inversiones; no se digita.'});
const preBlock=()=>'<div class="mk-formgrid mk-mt">'+preFld('Emisor','pre-emisor')+preFld('Moneda','pre-mon')+preFld('Valor indicativo','pre-val')+'</div><div class="mk-mt">'+srcChip('newinv')+'</div>';
function bindPre(f,name){const i=$('[name="'+name+'"]',f);if(!i)return;const up=()=>{const v=i.value.trim();if(!v){['pre-emisor','pre-mon','pre-val'].forEach(n=>{$('[name="'+n+'"]',f).value=''});return}const p=preload('newinv','instr:'+v).data;$('[name="pre-emisor"]',f).value=p.emisor;$('[name="pre-mon"]',f).value=p.moneda;$('[name="pre-val"]',f).value=f2(p.valor)};['input','change','blur'].forEach(ev=>i.addEventListener(ev,up));f.addEventListener('click',()=>setTimeout(up,60));up()}
/* Liquidez esperada (Administración del fondo) bajo Flujos futuros */
function flowsExtra(host,port,fac){const p=preload('adminfondo','flujos',port),sum=p.data.reduce((a,x)=>a+x.neto*fac,0);
 host.innerHTML='<div class="mk-card mk-mt"><h3 style="margin:0 0 8px;font-size:14px">'+(vehKind(port)==='fvp'?loc('Liquidez esperada del FVP (aportes y retiros netos)'):'Liquidez esperada del portafolio (aportes y retiros netos)')+'</h3><div class="mk-mb">'+srcChip('adminfondo')+'</div><div id="lq"></div></div>';
 DataTable($('#lq',host),{cols:[{h:'Mes',k:'mes'},{h:'Aportes y retiros netos esperados',k:'neto',html:x=>valC(x.neto,f0(x.neto)),txt:x=>f0(x.neto)}],rows:()=>p.data.map(x=>({mes:x.mes,neto:x.neto*fac})),noPage:true,noFilters:true,fileName:'liquidez-esperada',noun:'meses',totals:()=>['Total',valC(sum,f0(sum))]});
 const k=vehKind(port);
 if(k==='inm'||k==='alt'){const q=preload('adminactivos','flujos',port),cols=k==='inm'?[{h:'Mes',k:'mes'},{h:'Canon esperado',k:'canon',fmt:f0},{h:'Pérdida esperada',k:'perdida',fmt:f0},{h:'Canon neto esperado',k:'neto',fmt:f0}]:[{h:'Mes',k:'mes'},{h:'Desembolsos esperados',k:'desemb',fmt:f0},{h:'Flujos esperados de TCC y cartera',k:'cartera',fmt:f0}],rws=q.data.map(x=>({mes:x.mes,canon:x.canon*fac,perdida:x.perdida*fac,neto:(x.canon-x.perdida)*fac,desemb:x.desemb*fac,cartera:x.cartera*fac}));
  host.insertAdjacentHTML('beforeend','<div class="mk-card mk-mt"><h3 style="margin:0 0 8px;font-size:14px">'+(k==='inm'?'Canon y pérdida esperados':'Desembolsos y flujos de cartera esperados')+'</h3><div class="mk-mb">'+srcChip('adminactivos')+'</div><div id="aa"></div></div>');
  DataTable($('#aa',host),{cols,rows:()=>rws,noPage:true,noFilters:true,fileName:k==='inm'?'canon-esperado':'desembolsos-esperados',noun:'meses',totals:rs=>['Total'].concat(cols.slice(1).map(cc=>f0(rs.reduce((s,x)=>s+x[cc.k],0))))})}
}
Object.assign(APO,{deriv:[['Exposición y cobertura','#/dashboard/exposure'],['Evaluación de límites','#/limit-control/limit-evaluation'],['Contrapartes y cupos','#/parametrizacion/counterparties'],['Libro de órdenes','#/orders/reports']]});
APO.flow.push(['Derivados','#/orders/derivatives']);APO.port.push(['Derivados','#/orders/derivatives']);APO.cp.push(['Derivados','#/orders/derivatives']);
const EVSEEN=new Set();
/* Flujo de órdenes: estados de derivados y decisiones, y parámetros editables */
function flowExtras(pg){
 const box=(s)=>'<div style="flex:1;min-width:170px;border:1px solid var(--mk-border);border-radius:10px;padding:14px;background:var(--mk-surface);text-align:center"><div>'+badge(s[0],s[1],true)+'</div><div class="mk-help" style="margin-top:8px">'+s[2]+'</div></div>';
 const arrow='<div style="display:flex;align-items:center;color:var(--mk-primary);font-size:24px;font-weight:700">→</div>';
 const Y='<span class="pos">Sí</span>',N='<span class="mk-na">No</span>';
 const tbl=(head,rows)=>'<div class="mk-tablewrap"><table class="mk-table"><thead><tr>'+head.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
 const DS_=[['En cotización','info','Se registran cotizaciones de contrapartes distintas y se comparan con el valor indicativo.'],['Por justificar','warning','Se eligió una cotización que no es la mejor o excede la tolerancia: falta la justificación.'],['Registrada','info','La orden se registró con su evidencia de mejor ejecución; falta confirmarla.'],['Confirmada','success','Otro usuario la confirmó (segregación de funciones). Se publica “Orden ejecutada”.']];
 const ID_=[['Propuesta','info','El proponente registra la decisión con su monto y el número de acta; se valida la concentración.'],['En comité','warning','El comité revisa la propuesta; el aprobador es distinto del proponente.'],['Aprobada','success','Acta inmutable. Se publica el evento “Decisión aprobada”.'],['Rechazada','danger','El comité no aprueba; queda registrada y no se puede reabrir.']];
 pg.insertAdjacentHTML('beforeend','<div class="mk-subhead mk-mt">'+ic('layers')+'Ciclo de vida de una orden de derivados</div><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:stretch">'+box(DS_[0])+arrow+box(DS_[1])+arrow+box(DS_[2])+arrow+box(DS_[3])+'</div><div class="mk-help mk-mt">Desde En cotización, Por justificar o Registrada también se puede anular; la evidencia de la orden anulada se conserva.</div>'
  +'<div class="mk-subhead mk-mt">'+ic('check')+'Acciones permitidas por estado (derivados)</div>'+tbl(['Estado','Ver detalle','Continuar orden','Confirmar','Ver evidencia','Anular','Siguiente estado'],[[badge('En cotización','info',true),Y,Y,N,N,Y,'Por justificar o Registrada'],[badge('Por justificar','warning',true),Y,Y,N,N,Y,'Registrada'],[badge('Registrada','info',true),Y,N,Y,Y,Y,'Confirmada'],[badge('Confirmada','success',true),Y,N,N,Y,N,'—'],[badge('Anulada','danger',true),Y,N,N,Y,N,'—']])
  +'<div class="mk-subhead mk-mt">'+ic('layers')+'Ciclo de vida de una decisión de inversión</div><div style="display:flex;gap:10px;flex-wrap:wrap;align-items:stretch">'+box(ID_[0])+arrow+box(ID_[1])+arrow+box(ID_[2])+'</div><div style="display:flex;gap:12px;margin-top:12px;align-items:center;flex-wrap:wrap"><span class="mk-help">Desde En comité también puede rechazarse:</span>'+arrow+'<div style="width:260px">'+box(ID_[3])+'</div></div>'
  +'<div class="mk-subhead mk-mt">'+ic('check')+'Acciones permitidas por estado (decisiones)</div>'+tbl(['Estado','Ver detalle','Editar','Enviar a comité','Aprobar o rechazar','Siguiente estado'],[[badge('Propuesta','info',true),Y,Y,Y,N,'En comité'],[badge('En comité','warning',true),Y,N,N,Y,'Aprobada o Rechazada'],[badge('Aprobada','success',true),Y,N,N,N,'— (acta inmutable)'],[badge('Rechazada','danger',true),Y,N,N,N,'—']])
  +'<fieldset class="mk-fieldset mk-mt" id="par"><legend>Parámetros de mejor ejecución y datos precargados</legend><div class="mk-mb">'+badge('Por definir con Compliance','warning')+' <span class="mk-help">Valores ilustrativos y editables; no son normas.</span></div><div class="mk-formgrid">'+inpF('p-min','Mínimo de cotizaciones de contrapartes distintas',String(PARAMS.minQuotes),{req:true})+inpF('p-tol','Tolerancia frente al valor indicativo (%)',String(PARAMS.tol).replace('.',','),{req:true})+inpF('p-stale','Umbral de dato precargado desactualizado (días)',String(PARAMS.staleDays),{req:true})+inpF('p-val','Frecuencia de avalúo antes de marcar “vencida” (meses)',String(PARAMS.valMonths),{req:true})+'</div><div class="mk-mt"><button type="button" class="mk-btn" data-ps>'+ic('save')+'Guardar parámetros</button></div></fieldset>');
 $('[data-ps]',pg).addEventListener('click',()=>{const g=n=>$('[name="'+n+'"]',pg).value.trim().replace(',','.'),mn=parseInt(g('p-min'),10),tl=parseFloat(g('p-tol')),sd=parseInt(g('p-stale'),10),vm=parseInt(g('p-val'),10),errs=[];
  if(!(mn>=1))errs.push(['p-min','Debe ser 1 o más']);if(!(tl>=0))errs.push(['p-tol','Debe ser 0 o más']);if(!(sd>=0))errs.push(['p-stale','Debe ser 0 o más']);if(!(vm>=1))errs.push(['p-val','Debe ser 1 o más']);
  if(errs.length){errs.forEach(e=>errOn(pg,e[0],e[1]));toast('Revisa los parámetros marcados.','warning','Faltan datos');return}
  PARAMS.minQuotes=mn;PARAMS.tol=tl;PARAMS.staleDays=sd;PARAMS.valMonths=vm;toast('Parámetros guardados. Aplican a las nuevas órdenes y a los chips de fuente.','success','Parámetros guardados')});
 bindClear(pg);
}
