/* =============== FASE 1 · Órdenes › Derivados, evidencia y Dashboard › Exposición y cobertura =============== */
const DST={'En cotización':'info','Por justificar':'warning','Registrada':'info','Confirmada':'success','Anulada':'danger'};
const dEst=r=>badge(r.estado,DST[r.estado],true);
/* SUPUESTO: la mejor cotización es la de menor precio, tasa fija o prima (menor costo para el fondo). Ramiro confirma el criterio por instrumento. */
const rankQ=q=>q.slice().sort((a,b)=>a.precio-b.precio);
const subOpts=inst=>inst==='Swap'?[MM_RATES[2].code]:[dp().par];
const nowHM=()=>{const d=new Date();return String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')};
const desvPct=(p,ind)=>ind?(p-ind)/ind*100:0;
const evPad=()=>'EV-'+String(new Set(DERIV_EVID.map(e=>e.id)).size+1).padStart(4,'0');
AI.conf=['mk-iconbtn--ok','check','Confirmar orden'];AI.evid=['','doc','Ver evidencia'];
const estB=e=>badge(e,e==='Cumple'?'success':e==='Alerta'?'warning':'danger');
function limPanel(lim,st,withApproval){
 if(!lim)return '';
 let h='<div class="mk-subhead" style="margin-top:12px">'+ic('limits')+'Validación de límites</div><div class="mk-tablewrap"><table class="mk-table"><thead><tr><th>Límite</th><th>Naturaleza</th><th>Detalle</th><th>Resultado</th></tr></thead><tbody>'+lim.checks.map(c=>'<tr><td>'+esc(c.n)+'</td><td>'+natB(c.nat)+'</td><td>'+esc(c.det)+'</td><td>'+estB(c.estado)+'</td></tr>').join('')+'</tbody></table></div>';
 if(lim.blocked)h+='<div class="mk-mt">'+alertB('danger','Límite normativo excedido','La orden no puede continuar: los límites normativos bloquean.')+'</div>';
 else if(lim.needApproval&&withApproval)h+='<div class="mk-mt">'+alertB('warning','Límite interno excedido','Puedes continuar con una aprobación registrada: indica el motivo y quién aprueba.')+'</div><div class="mk-formgrid mk-mt">'+fld('Motivo de la excepción','<textarea class="mk-input" name="d-motivo" rows="2">'+esc(st.apr.motivo)+'</textarea>',{req:true,name:'d-motivo'})+fld('Aprobador','<div class="mk-combobox"><select class="mk-select" name="d-aprob"><option value="">Seleccionar</option>'+USERS.filter(u=>u!==USER.name).map(u=>'<option'+(st.apr.aprob===u?' selected':'')+'>'+esc(u)+'</option>').join('')+'</select></div>',{req:true,name:'d-aprob',tip:'El aprobador es distinto de quien registra la orden.'})+'</div>';
 return h;
}
function evExcess(lim,ref){lim.checks.filter(c=>c.estado==='Excedido').forEach(c=>publishEvent('Límite excedido',ref,c.n+' ('+c.nat+'): '+c.det,'cumplimiento'))}

function derivWizard(order,rp){
 const st={step:order?(order.estado==='Por justificar'?3:2):0,port:order?order.port:'',inst:order?order.inst:'',sub:order?order.sub:'',noc:order?order.noc:'',plazo:order?order.plazo:90,prop:order?order.prop:'Cobertura',quotes:order?order.quotes.map(q=>Object.assign({},q)):[],chosen:order?order.cp:null,just:order?order.just:'',lim:null,apr:{motivo:'',aprob:''},done:null};
 const steps=[['Iniciar','Portafolio e instrumento'],['Valor indicativo','Referencia de Derivados'],['Cotizaciones','Mínimo '+PARAMS.minQuotes+' contrapartes'],['Elegir','Comparar y justificar'],['Registrar','Límites y evidencia']];
 const m=openModal({title:order?'Continuar orden '+order.id:'Nueva orden de derivado',cls:'mk-modal--wizard',sticky:true,sub:'Cotiza, compara con el valor indicativo y registra con evidencia de mejor ejecución.',body:'',foot:''});
 const req=()=>({port:st.port,inst:st.inst,sub:st.sub,noc:okNum(st.noc),plazo:parseInt(st.plazo,10)||0,prop:st.prop});
 const wiz=()=>'<div class="mk-wizsteps">'+steps.map((s,i)=>(i?'<div class="mk-wizline'+(i<=st.step?' done':'')+'"></div>':'')+'<div class="mk-wizstep'+(i===st.step?' on':i<st.step?' done':'')+'"><div class="mk-wizstep__n">'+(i<st.step?'✓':i+1)+'</div><div class="mk-wizstep__t">'+s[0]+'</div><div class="mk-wizstep__d">'+s[1]+'</div></div>').join('')+'</div>';
 const val=n=>{const e=$('[name="'+n+'"]',m.el);return e?e.value.trim():''};
 const collect=()=>{if(st.step===0&&$('[name="d-port"]',m.el)){st.port=val('d-port');st.inst=val('d-inst');st.sub=val('d-sub');st.noc=val('d-noc');st.plazo=val('d-plazo');st.prop=rv(m.el,'d-prop')||st.prop}
  if($('[name="d-motivo"]',m.el)){st.apr.motivo=val('d-motivo');st.apr.aprob=val('d-aprob')}
  if(st.step===3){const c=rv(m.el,'d-ch');if(c)st.chosen=c;if($('[name="d-just"]',m.el))st.just=val('d-just')}};
 const flags=()=>{const ind=derivIndicative(req()),q=st.quotes.find(x=>x.cp===st.chosen),best=rankQ(st.quotes)[0];const dv=q?desvPct(q.precio,ind.valor):0;const notBest=q&&best&&q.cp!==best.cp,outTol=q&&Math.abs(dv)>PARAMS.tol;return {ind,q,best,dv,notBest,outTol,needJust:!!(notBest||outTol)}};
 const saveDraft=()=>{collect();const f=st.chosen?flags():null,estado=(f&&f.needJust&&!st.just.trim())?'Por justificar':'En cotización';
  const o=order||{id:nextId('DV',DERIV_ORDERS),fecha:Date.now(),uReg:USER.name,uConf:null,evId:null,apr:null};
  Object.assign(o,{port:st.port,inst:st.inst,sub:st.sub,noc:okNum(st.noc),plazo:parseInt(st.plazo,10),prop:st.prop,quotes:st.quotes.map(q=>Object.assign({},q)),cp:st.chosen,precio:f&&f.q?f.q.precio:null,just:st.just,estado});
  if(!order)DERIV_ORDERS.unshift(o);order=o;rp&&rp();m.close();toast('La orden '+o.id+' quedó en estado '+estado+'. Puedes continuarla después.','info','Borrador guardado')};
 const render=()=>{let b='',ft='',r=req();
  if(st.done){m.body.innerHTML=wiz().replace(/mk-wizstep(\s|")/g,'mk-wizstep done$1')+'<div class="mk-wizpanel">'+alertB('success','Orden registrada','La orden <b>'+st.done.o.id+'</b> quedó en estado <b>Registrada</b> y se generó la evidencia <b>'+st.done.ev.id+'</b>, ligada a la orden.')+'<div class="mk-formgrid mk-mt">'+fdRow('Contraparte',esc(st.done.o.cp))+fdRow('Precio',fmtInd(st.done.o.precio,st.done.ev.unidad))+fdRow('Valor indicativo',fmtInd(st.done.ev.indicativo,st.done.ev.unidad))+fdRow('Registró',esc(USER.name))+'</div></div>';m.foot.innerHTML='<button class="mk-btn mk-btn--secondary" data-c>Cerrar</button><button class="mk-btn" data-ev>'+ic('doc')+'Ver evidencia</button>';return}
  if(st.step===0){const pd=Array.from(new Set(DERIV_EXPO.map(e=>e.port))).concat(FUNDS.filter(f=>!DERIV_EXPO.some(e=>e.port===f)));
   b=wiz()+'<div class="mk-wizpanel"><div class="mk-formgrid">'+selF('d-port','Portafolio',pd,st.port,{req:true})+selF('d-inst','Instrumento',DERIV_INST(),st.inst,{req:true})+selF('d-sub','Subyacente',st.inst?subOpts(st.inst):[],st.sub,{req:true,tip:'Par de divisas para forward, opción y futuro; tasa de referencia para swap.'})+inpF('d-noc','Nocional ('+dp().mon+')',st.noc,{req:true,ph:'Ej: 2000000000'})+inpF('d-plazo','Plazo (días)',st.plazo,{req:true})+radiosF('d-prop','Propósito',['Cobertura','Posición propia'],st.prop,{req:true,tip:'Un portafolio configurado como solo cobertura no puede abrir posición propia.'})+'</div>'+limPanel(st.lim,st,false)+'</div>';
   ft='<div class="mk-wizfoot" style="width:100%;padding:0"><button class="mk-btn mk-btn--secondary" data-c>Cancelar</button><button class="mk-btn" data-n>Continuar</button></div>'}
  else if(st.step===1){const p=preload('derivados','indicativo',r),ind=p.data;
   b=wiz()+'<div class="mk-wizpanel"><div class="mk-formgrid">'+fdRow('Instrumento',esc(r.inst+' · '+r.sub))+fdRow('Nocional',money(r.noc))+fdRow('Plazo',r.plazo+' días')+fdRow('Valor indicativo','<b>'+fmtInd(ind.valor,ind.unidad)+'</b> '+esc(ind.unidad))+fdRow('Curva utilizada',esc(ind.curva))+fdRow('Fecha de la curva',fmtD(ind.fecha))+'</div><div class="mk-mt">'+srcChip('derivados')+'</div><p class="mk-help mk-mt">Dato de mercado ilustrativo, calculado con las tasas de referencia de Parametrización. El gestor no lo digita: viene de Derivados.</p></div>';
   ft='<div class="mk-wizfoot" style="width:100%;padding:0"><button class="mk-btn mk-btn--secondary" data-b>Atrás</button><button class="mk-btn" data-n>Continuar</button></div>'}
  else if(st.step===2){const ind=derivIndicative(r),used=st.quotes.map(q=>q.cp),avail=cpNames().filter(c=>!used.includes(c)),rk=rankQ(st.quotes),distinct=new Set(used).size;
   b=wiz()+'<div class="mk-wizpanel"><div class="mk-help mk-mb">Valor indicativo: <b>'+fmtInd(ind.valor,ind.unidad)+'</b> '+esc(ind.unidad)+' · tolerancia '+PARAMS.tol.toFixed(2).replace('.',',')+' % · cotizaciones requeridas: '+PARAMS.minQuotes+' ('+distinct+' registradas)</div><div class="mk-formgrid">'+fld('Contraparte','<div class="mk-combobox"><select class="mk-select" name="q-cp"><option value="">Seleccionar</option>'+avail.map(c=>'<option>'+esc(c)+'</option>').join('')+'</select></div>',{name:'q-cp'})+inpF('q-precio','Precio / tasa / prima',"",{ph:'Ej: '+f2(ind.valor)})+fld('Hora','<input class="mk-input" type="time" name="q-hora" value="'+nowHM()+'">',{name:'q-hora'})+selF('q-fuente','Fuente de la cotización',['Teléfono','Chat','Plataforma'],'Plataforma')+'</div><div class="mk-mt" style="display:flex;gap:10px"><button type="button" class="mk-btn" data-add>'+ic('plus')+'Agregar cotización</button><button type="button" class="mk-btn mk-btn--secondary" data-demo'+TIP('Agrega cotizaciones ilustrativas de tres contrapartes, para la demo')+'>Cargar cotizaciones de ejemplo</button></div>'
    +(rk.length?'<div class="mk-tablewrap mk-mt"><table class="mk-table"><thead><tr><th>#</th><th>Contraparte</th><th>Precio</th><th>Δ vs indicativo</th><th>Hora</th><th>Fuente</th><th></th></tr></thead><tbody>'+rk.map((q,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc(q.cp)+(i===0?' '+badge('Mejor','success'):'')+'</td><td>'+fmtInd(q.precio,ind.unidad)+'</td><td>'+(desvPct(q.precio,ind.valor)>=0?'+':'')+f2(desvPct(q.precio,ind.valor))+' %</td><td>'+esc(q.hora)+'</td><td>'+esc(q.fuente)+'</td><td><button type="button" class="mk-iconbtn mk-iconbtn--delete" data-del="'+esc(q.cp)+'" aria-label="Quitar cotización">'+ic('trash')+'</button></td></tr>').join('')+'</tbody></table></div>':'<div class="mk-empty mk-mt">Aún no hay cotizaciones registradas.</div>')+'</div>';
   ft='<div class="mk-wizfoot" style="width:100%;padding:0"><button class="mk-btn mk-btn--secondary" data-b>Atrás</button><span style="display:flex;gap:10px"><button class="mk-btn mk-btn--outline" data-draft>Guardar y continuar después</button><button class="mk-btn" data-n>Continuar</button></span></div>'}
  else if(st.step===3){const rk=rankQ(st.quotes);if(!st.chosen||!rk.some(q=>q.cp===st.chosen))st.chosen=rk[0].cp;const f=flags();
   b=wiz()+'<div class="mk-wizpanel"><div class="mk-tablewrap"><table class="mk-table"><thead><tr><th></th><th>Contraparte</th><th>Precio</th><th>Δ vs indicativo</th></tr></thead><tbody>'+rk.map((q,i)=>'<tr><td><input type="radio" name="d-ch" value="'+esc(q.cp)+'"'+(q.cp===st.chosen?' checked':'')+'></td><td>'+esc(q.cp)+(i===0?' '+badge('Mejor','success'):'')+'</td><td>'+fmtInd(q.precio,f.ind.unidad)+'</td><td>'+(desvPct(q.precio,f.ind.valor)>=0?'+':'')+f2(desvPct(q.precio,f.ind.valor))+' %</td></tr>').join('')+'</tbody></table></div>'
    +'<div class="mk-mt">'+(f.needJust?alertB('warning','Se requiere justificación',(f.notBest?'La cotización elegida no es la mejor. ':'')+(f.outTol?'Queda fuera de la tolerancia de '+PARAMS.tol.toFixed(2).replace('.',',')+' % frente al valor indicativo ('+f2(f.dv)+' %). ':'')+'Escribe el motivo: quedará en la evidencia.'):alertB('success','','La cotización elegida es la mejor y está dentro de la tolerancia: no requiere justificación.'))+'</div>'
    +(f.needJust?fld('Justificación','<textarea class="mk-input" name="d-just" rows="3" placeholder="Motivo de elegir esta cotización">'+esc(st.just)+'</textarea>',{req:true,name:'d-just'}):'')+'</div>';
   ft='<div class="mk-wizfoot" style="width:100%;padding:0"><button class="mk-btn mk-btn--secondary" data-b>Atrás</button><span style="display:flex;gap:10px"><button class="mk-btn mk-btn--outline" data-draft>Guardar y continuar después</button><button class="mk-btn" data-n>Continuar</button></span></div>'}
  else{const f=flags();if(!st.lim)st.lim=limitCheck(r,st.chosen);
   b=wiz()+'<div class="mk-wizpanel"><div class="mk-formgrid">'+fdRow('Portafolio',esc(r.port))+fdRow('Instrumento',esc(r.inst+' · '+r.sub))+fdRow('Nocional',money(r.noc))+fdRow('Plazo',r.plazo+' días')+fdRow('Propósito',r.prop)+fdRow('Contraparte elegida',esc(st.chosen))+fdRow('Precio elegido',fmtInd(f.q.precio,f.ind.unidad))+fdRow('Valor indicativo',fmtInd(f.ind.valor,f.ind.unidad))+fdRow('Usuario que registra',esc(USER.name))+fdRow('Justificación',esc(st.just||'No requerida'))+'</div>'+limPanel(st.lim,st,true)+'</div>';
   ft='<div class="mk-wizfoot" style="width:100%;padding:0"><button class="mk-btn mk-btn--secondary" data-b>Atrás</button><button class="mk-btn" data-reg'+(st.lim.blocked?' disabled':'')+'>Registrar orden</button></div>'}
  m.body.innerHTML=b;m.foot.innerHTML=ft};
 const alertIn=(t,x)=>{const p=$('.mk-wizpanel',m.el);const old=$('[data-wa]',p);if(old)old.remove();p.insertAdjacentHTML('beforeend','<div class="mk-mt" data-wa>'+alertB('danger',t,x)+'</div>')};
 const checkStep0=()=>{collect();const r=req(),errs=[];if(!r.port)errs.push('Portafolio');if(!r.inst)errs.push('Instrumento');if(!r.sub)errs.push('Subyacente');if(!(r.noc>0))errs.push('Nocional');if(!(r.plazo>=1))errs.push('Plazo');if(errs.length){toast('Completa: '+errs.join(', ')+'.','warning','Faltan datos');return false}
  st.lim=limitCheck(r);evExcess(st.lim,'previa · '+r.port);if(st.lim.blocked){render();toast('Límite normativo excedido: la orden no puede continuar.','danger','Orden bloqueada');return false}return true};
 m.el.addEventListener('change',e=>{if(e.target.name==='d-inst'){collect();st.sub=st.inst?subOpts(st.inst)[0]:'';render()}else if(e.target.name==='d-ch'){collect();render()}});
 m.el.addEventListener('click',e=>{const t=e.target.closest('button,[data-c],[data-x]');if(!t)return;
  if(t.matches('[data-c]')){m.close();return}
  if(t.matches('[data-b]')){collect();st.step--;st.lim=null;render();return}
  if(t.matches('[data-ev]')){const id=st.done.o.id;m.close();evidenceView(id);return}
  if(t.matches('[data-demo]')){const ind=derivIndicative(req()),k=/%/.test(ind.unidad)?0.002*ind.valor:ind.valor*0.0012,used=st.quotes.map(q=>q.cp),cps=QCPS.map(loc).filter(c=>cpNames().includes(c)&&!used.includes(c));cps.slice(0,Math.max(0,PARAMS.minQuotes-used.length)).forEach((c,i)=>st.quotes.push({cp:c,precio:+(ind.valor+(i-1)*k).toFixed(4),hora:['09:42','10:05','10:31'][i],fuente:['Teléfono','Plataforma','Chat'][i]}));render();return}
  if(t.matches('[data-add]')){const cp=val('q-cp'),pr=okNum(val('q-precio')),hr=val('q-hora'),fu=val('q-fuente');if(!cp||!(pr>0)){toast('Indica la contraparte y un precio mayor a 0.','warning','Faltan datos');return}if(st.quotes.some(q=>q.cp===cp)){toast('Esa contraparte ya cotizó: se requieren contrapartes distintas.','warning','Cotización repetida');return}st.quotes.push({cp,precio:pr,hora:hr||nowHM(),fuente:fu||'Plataforma'});render();return}
  if(t.matches('[data-del]')){st.quotes=st.quotes.filter(q=>q.cp!==t.dataset.del);render();return}
  if(t.matches('[data-draft]')){saveDraft();return}
  if(t.matches('[data-n]')){
   if(st.step===0){if(!checkStep0())return}
   else if(st.step===2){const n=new Set(st.quotes.map(q=>q.cp)).size;if(n<PARAMS.minQuotes){alertIn('Faltan cotizaciones','Se requieren al menos '+PARAMS.minQuotes+' cotizaciones de contrapartes distintas (hay '+n+').');toast('Se requieren al menos '+PARAMS.minQuotes+' cotizaciones de contrapartes distintas (hay '+n+').','warning','Cotizaciones insuficientes');return}}
   else if(st.step===3){collect();const f=flags();if(f.needJust&&!st.just.trim()){errOn(m.el,'d-just','La justificación es obligatoria');alertIn('Justificación obligatoria','La cotización elegida no es la mejor o excede la tolerancia: escribe la justificación para continuar.');toast('Escribe la justificación para continuar.','warning','Justificación obligatoria');return}}
   st.step++;if(st.step===4)st.lim=null;render();return}
  if(t.matches('[data-reg]')){collect();const r=req();st.lim=limitCheck(r,st.chosen);
   if(st.lim.blocked){evExcess(st.lim,'registro · '+r.port);render();toast('Límite normativo excedido: no se puede registrar la orden.','danger','Orden bloqueada');return}
   if(st.lim.needApproval&&(!st.apr.motivo||!st.apr.aprob)){render();if(!st.apr.motivo)errOn(m.el,'d-motivo','Indica el motivo');if(!st.apr.aprob)errOn(m.el,'d-aprob','Selecciona el aprobador');toast('Límite interno excedido: registra el motivo y el aprobador.','warning','Falta la aprobación');return}
   const f=flags(),ev={id:evPad(),ord:null,ver:1,cp:st.chosen,precio:f.q.precio,hora:f.q.hora,indicativo:f.ind.valor,unidad:f.ind.unidad,mejor:f.best.cp,just:st.just,user:USER.name,fecha:Date.now(),quotes:st.quotes.map(q=>Object.assign({},q)),nota:''};
   const o=order||{id:nextId('DV',DERIV_ORDERS),fecha:Date.now()};
   Object.assign(o,{port:r.port,inst:r.inst,sub:r.sub,noc:r.noc,plazo:r.plazo,prop:r.prop,quotes:ev.quotes,cp:st.chosen,precio:f.q.precio,just:st.just,estado:'Registrada',uReg:USER.name,uConf:null,evId:ev.id,apr:st.lim.needApproval?{motivo:st.apr.motivo,aprobador:st.apr.aprob}:null});
   if(!order)DERIV_ORDERS.unshift(o);ev.ord=o.id;DERIV_EVID.push(ev);
   DERIV_POS.push({ord:o.id,port:o.port,inst:o.inst,sub:o.sub,noc:o.noc,plazo:o.plazo,rest:Math.max(3,Math.round(o.plazo*0.9)),prop:o.prop,cp:o.cp,mtm:0,delta:o.inst==='Opción'?0.5:null,vega:o.inst==='Opción'?100000:null});
   st.lim.checks.filter(c=>c.estado==='Excedido').forEach(c=>publishEvent('Límite excedido',o.id,c.n+' ('+c.nat+'): '+c.det+(c.nat==='Interno'?' · aprobado por '+st.apr.aprob+': '+st.apr.motivo:''),'cumplimiento'));
   st.done={o,ev};order=o;rp&&rp();render();toast('Orden '+o.id+' registrada. Evidencia '+ev.id+'.','success','Orden registrada');return}
 });
 render();
}
function confirmDeriv(r,rp){
 const m=openModal({title:'Confirmar orden '+r.id,sub:'Segregación de funciones: quien registra la orden no la confirma.',body:'<div class="mk-formgrid">'+fdRow('Registró',esc(r.uReg))+fdRow('Contraparte',esc(r.cp))+fdRow('Nocional',money(r.noc))+fld('Usuario que confirma','<div class="mk-combobox"><select class="mk-select" name="uc"><option value="">Seleccionar</option>'+USERS.filter(u=>u!==r.uReg).map(u=>'<option>'+esc(u)+'</option>').join('')+'</select></div>',{req:true,name:'uc'})+'</div>',foot:'<button class="mk-btn mk-btn--secondary" data-c>Cancelar</button><button class="mk-btn" data-ok>'+ic('check')+'Confirmar</button>'});
 $('[data-c]',m.el).addEventListener('click',m.close);
 $('[data-ok]',m.el).addEventListener('click',()=>{const u=$('[name=uc]',m.el).value;if(!u){errOn(m.el,'uc','Selecciona quién confirma');return}if(u===r.uReg){errOn(m.el,'uc','Quien registra no puede confirmar');return}r.estado='Confirmada';r.uConf=u;publishEvent('Orden ejecutada',r.id,r.inst+' '+r.sub+' · '+r.port+' · confirmada por '+u,'contabilidad');m.close();rp&&rp();toast('La orden '+r.id+' quedó confirmada. Se publicó el evento “Orden ejecutada”.','success','Orden confirmada')});
}
/* Evidencia de mejor ejecución: inmutable. "Corregir" crea una versión nueva y conserva la anterior. */
function evidenceView(ordId){
 const vs=()=>DERIV_EVID.filter(e=>e.ord===ordId).sort((a,b)=>b.ver-a.ver);if(!vs().length){toast('La orden aún no tiene evidencia.','warning');return}
 let cur=vs()[0];const m=openModal({title:'Evidencia de mejor ejecución',cls:'mk-modal--form',sticky:true,body:'',foot:''});
 const draw=()=>{const latest=cur.ver===vs()[0].ver,dv=desvPct(cur.precio,cur.indicativo);
  m.body.innerHTML='<div style="margin-bottom:10px;display:flex;gap:8px;flex-wrap:wrap">'+badge(cur.id,'info')+badge('Versión '+cur.ver+(latest?' · vigente':' · histórica'),latest?'success':'neutral')+badge('Inmutable','neutral')+'</div><div class="mk-formgrid">'+fdRow('Orden',esc(cur.ord))+fdRow('Contraparte elegida',esc(cur.cp))+fdRow('Precio elegido',fmtInd(cur.precio,cur.unidad))+fdRow('Hora',esc(cur.hora||'—'))+fdRow('Valor indicativo',fmtInd(cur.indicativo,cur.unidad))+fdRow('Desviación vs indicativo',(dv>=0?'+':'')+f2(dv)+' %')+fdRow('Mejor cotización',esc(cur.mejor))+fdRow('Registró',esc(cur.user))+fdRow('Fecha',new Date(cur.fecha).toLocaleString('es-ES'))+fdRow('Justificación',esc(cur.just||'No requerida'))+(cur.nota?fdRow('Nota',esc(cur.nota)):'')+'</div><div class="mk-subhead mk-mt">'+ic('scale')+'Cotizaciones recibidas</div><div class="mk-tablewrap"><table class="mk-table"><thead><tr><th>Contraparte</th><th>Precio</th><th>Hora</th><th>Fuente</th><th>Elegida</th></tr></thead><tbody>'+rankQ(cur.quotes).map(q=>'<tr><td>'+esc(q.cp)+'</td><td>'+fmtInd(q.precio,cur.unidad)+'</td><td>'+esc(q.hora)+'</td><td>'+esc(q.fuente)+'</td><td>'+(q.cp===cur.cp?badge('Sí','success'):'—')+'</td></tr>').join('')+'</tbody></table></div>'
   +(vs().length>1?'<div class="mk-subhead mk-mt">'+ic('refresh')+'Versiones</div><div style="display:flex;gap:8px;flex-wrap:wrap">'+vs().map(v=>'<button type="button" class="mk-btn '+(v.ver===cur.ver?'':'mk-btn--secondary')+'" data-v="'+v.ver+'">Versión '+v.ver+'</button>').join('')+'</div>':'');
  m.foot.innerHTML='<button class="mk-btn mk-btn--secondary" data-c>Cerrar</button><button class="mk-btn mk-btn--secondary" data-pr>'+ic('doc')+'Imprimir</button><button class="mk-btn mk-btn--secondary" data-xc>CSV</button><button class="mk-btn mk-btn--excel" data-xx>Excel</button>'+(latest?'<button class="mk-btn" data-fix'+TIP('No se edita: crea la versión siguiente y conserva la anterior')+'>Corregir</button>':'');
  $$('[data-v]',m.body).forEach(b=>b.addEventListener('click',()=>{cur=vs().find(v=>v.ver===+b.dataset.v);draw()}));
  $('[data-c]',m.foot).addEventListener('click',m.close);
  $('[data-pr]',m.foot).addEventListener('click',()=>{m.el.classList.add('is-printing');window.print();setTimeout(()=>m.el.classList.remove('is-printing'),500)});
  const exp=fmt=>{const heads=['Evidencia','Versión','Orden','Contraparte','Precio','Hora','Fuente','Elegida','Valor indicativo','Mejor cotización','Justificación','Registró'];exportTable('evidencia-'+cur.id+'-v'+cur.ver,fmt,heads,rankQ(cur.quotes).map(q=>[cur.id,{n:cur.ver,s:2},cur.ord,q.cp,{n:q.precio,s:2},q.hora,q.fuente,q.cp===cur.cp?'Sí':'No',{n:cur.indicativo,s:2},cur.mejor,cur.just||'No requerida',cur.user]),'Evidencia');toast('Evidencia exportada.','success','Descarga lista')};
  $('[data-xc]',m.foot).addEventListener('click',()=>exp('csv'));$('[data-xx]',m.foot).addEventListener('click',()=>exp('xlsx'));
  const fx=$('[data-fix]',m.foot);if(fx)fx.addEventListener('click',()=>{const f=openModal({z:80,title:'Corregir la evidencia',sub:'Se crea la versión '+(cur.ver+1)+'; la versión '+cur.ver+' se conserva sin cambios.',body:'<div class="mk-formgrid">'+fld('Cotización elegida','<div class="mk-combobox"><select class="mk-select" name="fx-cp">'+rankQ(cur.quotes).map(q=>'<option'+(q.cp===cur.cp?' selected':'')+'>'+esc(q.cp)+'</option>').join('')+'</select></div>',{req:true,name:'fx-cp'})+fld('Justificación de la corrección','<textarea class="mk-input" name="fx-j" rows="3"></textarea>',{req:true,name:'fx-j'})+'</div>',foot:'<button class="mk-btn mk-btn--secondary" data-c>Cancelar</button><button class="mk-btn" data-ok>'+ic('save')+'Guardar versión '+(cur.ver+1)+'</button>'});
   $('[data-c]',f.el).addEventListener('click',f.close);
   $('[data-ok]',f.el).addEventListener('click',()=>{const cp=$('[name=fx-cp]',f.el).value,j=$('[name=fx-j]',f.el).value.trim();if(!j){errOn(f.el,'fx-j','Indica el motivo de la corrección');return}const q=cur.quotes.find(x=>x.cp===cp),best=rankQ(cur.quotes)[0];
    const nv=Object.assign({},cur,{ver:cur.ver+1,cp,precio:q.precio,hora:q.hora,mejor:best.cp,just:j,user:USER.name,fecha:Date.now(),quotes:cur.quotes.map(x=>Object.assign({},x)),nota:'Corrección de la versión '+cur.ver});DERIV_EVID.push(nv);
    const o=DERIV_ORDERS.find(x=>x.id===ordId);if(o){o.cp=cp;o.precio=q.precio;o.just=j}f.close();cur=nv;draw();toast('Se creó la versión '+nv.ver+' de la evidencia; la versión anterior se conserva.','success','Evidencia corregida')})});
 };
 draw();
}
const togDeriv=r=>({title:'Anular orden',danger:true,message:'Vas a anular la orden <b>'+esc(r.id)+'</b> ('+esc(r.inst)+' · '+esc(r.port)+'). Se retira su posición; la evidencia se conserva. Esta acción no se puede deshacer.',confirm:'Anular',done:'Orden anulada correctamente.',apply:()=>{r.estado='Anulada';for(let i=DERIV_POS.length-1;i>=0;i--)if(DERIV_POS[i].ord===r.id)DERIV_POS.splice(i,1)}});
PAGES.deriv=crudPage({title:'Derivados',help:'Cotiza, compara con el valor indicativo, registra y confirma operaciones de cobertura o posición propia, con su evidencia de mejor ejecución.',newLabel:'Nueva orden',apoya:APO.deriv,dateRange:{k:'fecha',label:'fecha de creación'},entity:'orden de derivado',entityArt:'La orden',fileName:'derivados',defaultSort:'Creado',defaultDir:-1,searchPh:'N° de orden, portafolio, subyacente o contraparte...',noun:'órdenes',
 filters:[{id:'port',label:'Portafolio',opts:()=>Array.from(new Set(DERIV_ORDERS.map(o=>o.port))),get:r=>r.port},{id:'inst',label:'Instrumento',opts:()=>DERIV_INST(),get:r=>r.inst},{id:'prop',label:'Propósito',opts:()=>['Cobertura','Posición propia'],get:r=>r.prop},{id:'est',label:'Estado',opts:()=>DERIV_STATES,get:r=>r.estado}],
 kpis:rows=>[['En cotización',rows.filter(r=>r.estado==='En cotización').length,'b'],['Por justificar',rows.filter(r=>r.estado==='Por justificar').length,'y'],['Registradas',rows.filter(r=>r.estado==='Registrada').length,'p'],['Confirmadas',rows.filter(r=>r.estado==='Confirmada').length,'g'],['Anuladas',rows.filter(r=>r.estado==='Anulada').length,'r']],
 cols:[{h:'N° orden',k:'id',sortable:true},{h:'Portafolio',k:'port'},{h:'Instrumento',k:'inst',html:r=>badge(r.inst,'neutral'),txt:r=>r.inst},{h:'Subyacente',k:'sub'},{h:'Nocional',k:'noc',fmt:f0},{h:'Plazo (días)',k:'plazo'},{h:'Propósito',k:'prop',html:r=>badge(r.prop,r.prop==='Cobertura'?'success':'warning'),txt:r=>r.prop},{h:'Contraparte',k:'cp',fmt:v=>v||'—'},{h:'Evidencia',k:'evId',fmt:v=>v||'—'},{h:'Creado',k:'fecha',fmt:dstr,sortable:true}],
 rows:()=>DERIV_ORDERS,estado:dEst,
 acts:r=>{const a=[['ver']];if(r.estado==='En cotización'||r.estado==='Por justificar')a.push(['edit','Continuar orden']);if(r.evId)a.push(['evid']);if(r.estado==='Registrada')a.push(['conf']);if(r.estado!=='Confirmada'&&r.estado!=='Anulada')a.push(['anular','Anular orden']);return a},
 toggle:togDeriv,onNew:(rp)=>derivWizard(null,rp),onEdit:(r,rp)=>derivWizard(r,rp),
 onAct:(a,r,rp)=>{if(a==='evid')evidenceView(r.id);else if(a==='conf')confirmDeriv(r,rp)},
 detail:r=>[['N° de orden',r.id],['Portafolio',esc(r.port)],['Instrumento',esc(r.inst)],['Subyacente',esc(r.sub)],['Nocional',money(r.noc)],['Plazo',r.plazo+' días'],['Propósito',r.prop],['Contraparte',esc(r.cp||'—')],['Cotizaciones registradas',String(r.quotes.length)],['Registró',esc(r.uReg)],['Confirmó',esc(r.uConf||'—')],['Evidencia',esc(r.evId||'—')],['Justificación',esc(r.just||'No requerida')],['Aprobación de excepción',r.apr?esc(r.apr.aprobador+': '+r.apr.motivo):'—'],['Creada',dstr(r.fecha)],['Estado',r.estado]],badges:r=>dEst(r),detailTitle:r=>'Orden · '+r.id,
 form:()=>({html:'',read:()=>({ok:false})}),review:()=>[],onSave:()=>{}
});

/* ---------- Dashboard › Exposición y cobertura ---------- */
function exposureCalc(port,dt){const fac=dfac(dt),base=fromIso(dt);
 const lines=DERIV_EXPO.filter(e=>!port||e.port===port).map(e=>{const pos=DERIV_POS.filter(p=>p.port===e.port&&p.sub===e.sub),cob=pos.filter(p=>p.prop==='Cobertura').reduce((a,p)=>a+p.noc,0)*fac,bruta=e.bruta*fac;return {port:e.port,sub:e.sub,bruta,cob,desc:bruta-cob,pct:bruta?cob/bruta:0,mtm:pos.reduce((a,p)=>a+p.mtm,0)*fac,n:pos.length}});
 const posRows=DERIV_POS.filter(p=>!port||p.port===port).map(p=>Object.assign({},p,{noc:p.noc*fac,mtm:p.mtm*fac,venc:base+p.rest*864e5}));
 const S1=(a,f)=>a.reduce((x,y)=>x+f(y),0),bruta=S1(lines,l=>l.bruta),cob=S1(lines,l=>l.cob);
 return {lines,posRows,bruta,cob,pct:bruta?cob/bruta:0,neta:bruta-cob,mtm:S1(posRows,p=>p.mtm),v30:S1(posRows.filter(p=>p.prop==='Cobertura'&&p.rest<=30),p=>p.noc),n30:posRows.filter(p=>p.prop==='Cobertura'&&p.rest<=30).length}}
function coverSVG(items){const W=1100,Hh=240,m={l:16,r:16,t:30,b:44},iw=W-m.l-m.r,ih=Hh-m.t-m.b,n=items.length,bw=iw/n*0.4;let mx=0;items.forEach(i=>{mx=Math.max(mx,i.cob+i.desc)});mx=mx||1;
 let g='<line x1="'+m.l+'" x2="'+(W-m.r)+'" y1="'+(Hh-m.b)+'" y2="'+(Hh-m.b)+'" stroke="currentColor" opacity=".4"/>';
 items.forEach((it,i)=>{const x=m.l+iw/n*i+(iw/n-bw)/2,hc=ih*it.cob/mx,hd=ih*it.desc/mx,y0=Hh-m.b;g+='<rect x="'+x+'" y="'+(y0-hc)+'" width="'+bw+'" height="'+Math.max(hc,1)+'" rx="3" fill="#6A1B9A"><title>Cubierto: '+f0(it.cob)+'</title></rect><rect x="'+x+'" y="'+(y0-hc-hd)+'" width="'+bw+'" height="'+Math.max(hd,1)+'" rx="3" fill="#94A3B8"><title>Descubierto: '+f0(it.desc)+'</title></rect><text x="'+(x+bw/2)+'" y="'+(y0-hc-hd-8)+'" text-anchor="middle" class="chart-txt" style="font-weight:600">'+pct(it.cob/(it.cob+it.desc||1),1)+' cubierto</text><text x="'+(x+bw/2)+'" y="'+(Hh-m.b+20)+'" text-anchor="middle" class="chart-txt">'+esc(it.l)+'</text>'});
 return '<svg viewBox="0 0 '+W+' '+Hh+'" width="100%" style="display:block;max-height:250px" role="img" aria-label="Cubierto y descubierto por subyacente">'+g+'</svg><div class="lgd"><span><i style="background:#6A1B9A"></i>Cubierto</span><span><i style="background:#94A3B8"></i>Descubierto</span></div>'}
PAGES.exposure=function(view,meta){
 const pg=mountPage(view,meta,'Exposición y cobertura','Exposición bruta, cobertura con derivados, descubierto y valoración (MTM) por portafolio.');
 const ports=()=>Array.from(new Set(DERIV_EXPO.map(e=>e.port)));
 const st={port:'',op:OPDATE,done:true,tab:0};
 const draw=()=>{
  pg.innerHTML=queryBar(opField(st.op)+fld('Portafolio','<div class="mk-combobox"><select class="mk-select" name="port"><option value="">Todos los portafolios</option>'+ports().map(p=>'<option'+(p===st.port?' selected':'')+'>'+esc(p)+'</option>').join('')+'</select></div>',{name:'port'}))+'<div id="res"></div>';
  $('[name=port]',pg).addEventListener('change',e=>st.port=e.target.value);bindOp(pg,st,()=>{if(st.done)result()});
  $('[data-clear]',pg).addEventListener('click',()=>{st.port='';st.op=OPDATE;st.done=true;draw()});
  $('[data-consult]',pg).addEventListener('click',()=>{st.done=true;result()});
  result();
 };
 function result(){
  const c=exposureCalc(st.port,st.op),r=$('#res',pg);
  r.innerHTML='<div class="mk-mb" style="display:flex;gap:10px;flex-wrap:wrap">'+srcChip('newinv')+srcChip('derivados')+'</div><div class="mk-kpis">'+kpiBox('Exposición bruta',f0(c.bruta),'p','Valor de los activos expuestos al subyacente, según New Inversiones')+kpiBox('Cobertura (nocional)',f0(c.cob),'b','Nocional de los derivados con propósito de cobertura')+kpiBox('% cubierto','<span class="pos">'+pct(c.pct,1)+'</span>','g','Nocional de cobertura dividido por la exposición bruta')+kpiBox('Exposición neta',f0(c.neta),'y','Exposición bruta menos cobertura')+kpiBox('MTM de derivados',valC(c.mtm,f0(c.mtm)),c.mtm>=0?'g':'r','Valoración a mercado de las posiciones')+kpiBox('Vence en 30 días',f0(c.v30)+' · '+c.n30+' pos.','y','Cobertura que vence en el próximo mes')+'</div><div id="tabs"></div>';
  tabsUI($('#tabs',r),['Cubierto y descubierto','Posiciones de derivados'],st,(i,p)=>{
   if(i===0){const bySub={};c.lines.forEach(l=>{const b=bySub[l.sub]=bySub[l.sub]||{l:l.sub,cob:0,desc:0};b.cob+=l.cob;b.desc+=l.desc});
    p.innerHTML='<div class="mk-card mk-mb"><h3 style="margin:0 0 6px;font-size:14px">Cubierto frente a descubierto por subyacente</h3>'+coverSVG(Object.keys(bySub).map(k=>bySub[k]))+'</div><div id="t"></div>';
    DataTable($('#t',p),{cols:[{h:'Portafolio',k:'port',sortable:true},{h:'Subyacente',k:'sub',sortable:true},{h:'Exposición bruta',k:'bruta',fmt:f0},{h:'Cobertura',k:'cob',fmt:f0},{h:'Descubierto',k:'desc',fmt:f0},{h:'% cubierto',k:'pct',fmt:v=>pct(v,1),sortable:true},{h:'MTM',k:'mtm',html:x=>valC(x.mtm,f0(x.mtm)),txt:x=>f0(x.mtm)},{h:'Posiciones',k:'n'}],rows:()=>c.lines,noPage:true,fileName:'exposicion-cobertura',searchPh:'Portafolio o subyacente...',noun:'líneas',totals:rows=>['Total','',f0(rows.reduce((a,x)=>a+x.bruta,0)),f0(rows.reduce((a,x)=>a+x.cob,0)),f0(rows.reduce((a,x)=>a+x.desc,0)),pct(c.pct,1),valC(c.mtm,f0(c.mtm)),String(rows.reduce((a,x)=>a+x.n,0))]})}
   else{p.innerHTML='<div id="t"></div>';DataTable($('#t',p),{cols:[{h:'Orden',k:'ord',sortable:true},{h:'Portafolio',k:'port'},{h:'Instrumento',k:'inst',html:x=>badge(x.inst,'neutral'),txt:x=>x.inst},{h:'Subyacente',k:'sub'},{h:'Propósito',k:'prop'},{h:'Contraparte',k:'cp'},{h:'Nocional',k:'noc',fmt:f0},{h:'MTM',k:'mtm',html:x=>valC(x.mtm,f0(x.mtm)),txt:x=>f0(x.mtm)},{h:'Vencimiento',k:'venc',fmt:fmtD,sortable:true}],rows:()=>c.posRows,searchPh:'Orden, portafolio o contraparte...',fileName:'posiciones-derivados',noun:'posiciones',defaultSort:'Vencimiento'})}
  });
 }
 draw();
};
