/* =============== FASE 2 y 3 · límites, atribución por tipo de vehículo y ayudas =============== */
Object.assign(APO,{idec:[['Visor de portafolio','#/dashboard/graphics'],['Flujos futuros','#/dashboard/future-flows'],['Evaluación de límites','#/limit-control/limit-evaluation'],['Instrumentos','#/parametrizacion/instruments']]});
APO.port.push(['Decisiones de inversión','#/orders/investment-decisions']);
APO.instr.push(['Decisiones de inversión','#/orders/investment-decisions']);
APO.cat.push([['Decisiones de inversión','#/orders/investment-decisions'],['Instrumentos','#/parametrizacion/instruments']]);
APO.cat.push([['Derivados','#/orders/derivatives'],['Evaluación de límites','#/limit-control/limit-evaluation']]);
APO.limits.push(['Decisiones de inversión','#/orders/investment-decisions']);
/* Límites de activos no listados. SUPUESTO: las concentraciones y el tope por etapa son internos; el endeudamiento y el tope a activos en desarrollo se tratan como normativos. */
Object.assign(SUBLIMITS,{'CONCENTRACIÓN POR INMUEBLE':['INM-001','INM-002','INM-003'],'CONCENTRACIÓN POR ARRENDATARIO':['Operador de servicios financieros','Operador logístico regional','Cadena comercial líder'],'CONCENTRACIÓN POR CIUDAD':['Bogotá','Medellín','Barranquilla'],'ENDEUDAMIENTO MÁXIMO':['Endeudamiento sobre activo total'],'TOPE ACTIVOS EN DESARROLLO':['Activos en desarrollo'],'CONCENTRACIÓN POR ORIGINADOR':['Constructora Andina','Promotora del Valle','Originadora de Crédito Andina'],'CONCENTRACIÓN POR PROYECTO':['PRY-001','PRY-002','TCC-001'],'CONCENTRACIÓN POR SECTOR':['Infraestructura','Vivienda','Crédito hipotecario'],'TOPE POR ETAPA':['Preoperativa','Operativa']});
NAT_INT.push('CONCENTRACIÓN POR INMUEBLE','CONCENTRACIÓN POR ARRENDATARIO','CONCENTRACIÓN POR CIUDAD','CONCENTRACIÓN POR ORIGINADOR','CONCENTRACIÓN POR PROYECTO','CONCENTRACIÓN POR SECTOR','TOPE POR ETAPA');
[['CONCENTRACIÓN POR INMUEBLE','MAX',0.35,'INM-001','TOTAL ACTIVO','FONDO INMOBILIARIO 1',[2026,6,1]],['CONCENTRACIÓN POR ARRENDATARIO','MAX',0.40,'Operador logístico regional','TOTAL ACTIVO','FONDO INMOBILIARIO 1',[2026,6,1]],['CONCENTRACIÓN POR CIUDAD','MAX',0.55,'Bogotá','TOTAL ACTIVO','FONDO INMOBILIARIO 1',[2026,6,1]],['ENDEUDAMIENTO MÁXIMO','MAX',0.30,'Endeudamiento sobre activo total','TOTAL ACTIVO','FONDO INMOBILIARIO 1',[2026,6,1]],
 ['CONCENTRACIÓN POR ORIGINADOR','MAX',0.40,'Constructora Andina','TOTAL ACTIVO','FONDO ALTERNATIVO 1',[2026,6,15]],['CONCENTRACIÓN POR PROYECTO','MAX',0.35,'PRY-001','TOTAL ACTIVO','FONDO ALTERNATIVO 1',[2026,6,15]],['CONCENTRACIÓN POR SECTOR','MAX',0.50,'Infraestructura','TOTAL ACTIVO','FONDO ALTERNATIVO 1',[2026,6,15]],['TOPE ACTIVOS EN DESARROLLO','MAX',0.60,'Activos en desarrollo','TOTAL ACTIVO','FONDO ALTERNATIVO 1',[2026,6,15]],['TOPE POR ETAPA','MAX',0.70,'Preoperativa','TOTAL ACTIVO','FONDO ALTERNATIVO 1',[2026,6,15]]
].forEach(a=>LIMITS.push({tipo:a[0],eval:a[1],pct:a[2],sub:a[3],denom:a[4],port:a[5],fecha:mkDate(a[6][0],a[6][1],a[6][2]).getTime(),activo:true}));
const claseOpts=(port,sel)=>Array.from(new Set(holdingsFor(port).map(h=>h.ca))).map(c=>'<option'+(sel===c?' selected':'')+'>'+esc(c)+'</option>').join('');
/* Atribución por tipo de vehículo. SUPUESTO: cifras ilustrativas. */
function inmMetrics(port,per){const k=PERIODS[per].k;return INSTRUMENTS.filter(a=>a.clase==='Inmueble'&&a.port===port).map(a=>{const v=assetVal(a),rr=rng(hash(a.mnem+per)),renta=(0.0040+rr()*0.0014)*k,sorted=a.avaluos.slice().sort((x,y)=>y.fecha-x.fecha),val=sorted.length>1?(sorted[0].valor-sorted[1].valor)/sorted[1].valor*Math.min(1,k):0;return {a,port,valor:v.valor,renta,val,total:renta+val}})}
function altMetrics(port){return INSTRUMENTS.filter(a=>a.clase&&a.clase!=='Renta fija'&&a.clase!=='Inmueble'&&a.port===port&&a.comp!=null).map(a=>{const v=assetVal(a),distrib=a.flujoEsp*(a.etapa==='Operativa'?5.2:1.4),moic=(v.valor+distrib)/a.desemb,years=Math.max(0.6,(fromIso(OPDATE)-a.emi)/(365*864e5)),tir=Math.pow(moic,1/years)-1;return {a,port,desemb:a.desemb,valor:v.valor,distrib,moic,tir,years}})}
const stepSeries=pts=>{const n=pts.length,b=Math.max(1,Math.round(n/4));return pts.map((p,i)=>{const j=Math.min(n-1,Math.floor(i/b)*b);return {d:p.d,p:pts[j].p,b:pts[j].b}})};
function vehSummary(r,st){const vk=vehKind(st.port);if(vk!=='inm'&&vk!=='alt')return false;
 const s=perfStats(st.port,st.per,endOf(st.mes));
 if(vk==='inm'){const M=inmMetrics(st.port,st.per),tv=M.reduce((a,x)=>a+x.valor,0)||1,renta=M.reduce((a,x)=>a+x.renta*x.valor,0)/tv,val=M.reduce((a,x)=>a+x.val*x.valor,0)/tv,tot=renta+val,rb=s.rb,ex=tot-rb;
  r.innerHTML='<div class="mk-mb" style="display:flex;gap:10px;flex-wrap:wrap">'+srcChip('adminactivos')+'</div><div class="mk-kpis">'+kpiBox('Rentabilidad total','<span class="'+sgnCls(tot)+'">'+pcs(tot)+'</span>','p')+kpiBox('Renta (canon neto)',pcs(renta),'g','Canon neto de gastos del inmueble, sobre su valor')+kpiBox('Valorización',valC(val,pcs(val)),'b','Cambio del valor del inmueble entre avalúos')+kpiBox('Rentabilidad benchmark',pcs(rb),'','Benchmark del portafolio')+kpiBox('Exceso (alpha)',valC(ex,bps(ex)),'y')+'</div><div class="mk-mb">'+alertB('info','La serie de valorización es escalonada','El valor de los inmuebles cambia solo cuando se registra un avalúo (cada '+PARAMS.valMonths+' meses como máximo): por eso la rentabilidad no se mueve día a día.')+'</div><div class="mk-mt" id="tabs"></div>';
  tabsUI($('#tabs',r),['Renta y valorización','Evolución'],st,(i,p)=>{if(i===0){p.innerHTML='<div id="t"></div>';DataTable($('#t',p),{cols:[{h:'Inmueble',html:x=>esc(x.a.nombre),txt:x=>x.a.nombre,sv:x=>x.a.nombre},{h:'Ciudad',html:x=>esc(x.a.ciudad),txt:x=>x.a.ciudad},{h:'Valor vigente',k:'valor',fmt:f0},{h:'Renta (canon neto)',k:'renta',html:x=>pcs(x.renta),txt:x=>pct(x.renta,2)},{h:'Valorización',k:'val',html:x=>valC(x.val,pcs(x.val)),txt:x=>pct(x.val,2)},{h:'Rentabilidad total',k:'total',html:x=>valC(x.total,pcs(x.total)),txt:x=>pct(x.total,2)},{h:'Valoración',html:x=>valBadge({vencida:isValStale(assetVal(x.a).fecha)}),txt:x=>isValStale(assetVal(x.a).fecha)?'Valoración vencida':'Vigente'}],rows:()=>M,noPage:true,noFilters:true,fileName:'renta-valorizacion',noun:'inmuebles'})}
   else p.innerHTML='<div class="mk-card">'+lineSVG(stepSeries(s.series),[{k:'p',n:st.port,c:'#6A1B9A'},{k:'b',n:(BENCH_DEF.filter(b=>b.port===st.port)[0]||{bench:'Benchmark'}).bench,c:'#64748B'}])+'</div>'});
  return true}
 const M=altMetrics(st.port),des=M.reduce((a,x)=>a+x.desemb,0)||1,tv=M.reduce((a,x)=>a+x.valor,0),dist=M.reduce((a,x)=>a+x.distrib,0),moic=(tv+dist)/des,yrs=M.reduce((a,x)=>a+x.years*x.desemb,0)/des,tir=Math.pow(moic,1/Math.max(0.6,yrs))-1;
 r.innerHTML='<div class="mk-mb" style="display:flex;gap:10px;flex-wrap:wrap">'+srcChip('adminactivos')+'</div><div class="mk-kpis">'+kpiBox('TIR (E.A.)','<span class="'+sgnCls(tir)+'">'+pct(tir,2)+'</span>','p','Tasa interna de retorno de los flujos del portafolio desde cada desembolso')+kpiBox('MOIC',f2(moic)+' x','g','Múltiplo sobre el capital desembolsado: (valor actual + distribuciones) / desembolsado')+kpiBox('Capital desembolsado',f0(des),'b')+kpiBox('Valor actual',f0(tv),'y')+kpiBox('Distribuciones recibidas',f0(dist),'')+'</div><div class="mk-mb">'+alertB('info','Se mide con TIR y MOIC','En portafolios alternativos no se usa la rentabilidad ponderada por tiempo: los flujos son irregulares y el valor se actualiza por modelo o avalúo.')+'</div><div id="t"></div>';
 DataTable($('#t',r),{cols:[{h:'Activo',html:x=>esc(x.a.nombre),txt:x=>x.a.nombre,sv:x=>x.a.nombre},{h:'Clase',html:x=>esc(x.a.clase),txt:x=>x.a.clase},{h:'Desembolsado',k:'desemb',fmt:f0},{h:'Valor actual',k:'valor',fmt:f0},{h:'Distribuciones',k:'distrib',fmt:f0},{h:'MOIC',k:'moic',fmt:v=>f2(v)+' x',sortable:true},{h:'TIR (E.A.)',k:'tir',html:x=>valC(x.tir,pct(x.tir,2)),txt:x=>pct(x.tir,2),sortable:true}],rows:()=>M,noPage:true,noFilters:true,fileName:'tir-moic',noun:'activos'});
 return true}
function profilesTab(p,st){
 const E=endOf(st.mes),rows=FVP_PERFILES.map(pf=>{const name=FUNDS.find(f=>vehKind(f)==='fvp'&&new RegExp(pf.toUpperCase()).test(f)),s=perfStats(name,st.per,E);return {pf,name,s}});
 const pts=rows[0].s.series.map((x,i)=>({d:x.d,p0:rows[0].s.series[i].p,p1:rows[1].s.series[i].p,p2:rows[2].s.series[i].p}));
 p.innerHTML='<div class="mk-card mk-mb">'+lineSVG(pts,[{k:'p0',n:'Conservador',c:'#15803D'},{k:'p1',n:'Moderado',c:'#6A1B9A'},{k:'p2',n:'Agresivo',c:'#D97706'}])+'</div><div id="t"></div>';
 DataTable($('#t',p),{cols:[{h:'Perfil',k:'pf'},{h:'Portafolio',k:'name'},{h:'Rentabilidad',html:x=>valC(x.s.rp,pcs(x.s.rp)),txt:x=>pct(x.s.rp,2)},{h:'Benchmark',html:x=>valC(x.s.rb,pcs(x.s.rb)),txt:x=>pct(x.s.rb,2)},{h:'Exceso (pb)',html:x=>valC(x.s.ex,bps(x.s.ex)),txt:x=>bps(x.s.ex)},{h:'Volatilidad',html:x=>pct(x.s.vol,2),txt:x=>pct(x.s.vol,2)},{h:'Sharpe',html:x=>f2(x.s.sharpe),txt:x=>f2(x.s.sharpe)}],rows:()=>rows,noPage:true,noFilters:true,fileName:'comparacion-perfiles',noun:'perfiles'})}
/* Informes por tipo de vehículo */
function vehReportData(name,st,per,end){const P=v=>({n:v,s:4}),N=v=>({n:v,s:2}),pb=v=>N(v*10000);
 const pick=k=>st.port==='Todos'?FUNDS.filter(f=>vehKind(f)===k):FUNDS.filter(f=>f===st.port&&vehKind(f)===k).concat(st.port!=='Todos'&&vehKind(st.port)!==k?FUNDS.filter(f=>vehKind(f)===k):[]);
 if(/inmobiliarios/.test(name)){const rows=[];pick('inm').forEach(p=>inmMetrics(p,per).forEach(x=>rows.push([p,x.a.nombre,N(x.valor),P(x.renta),P(x.val),P(x.total)])));return {heads:['Portafolio','Inmueble','Valor vigente','Renta (canon neto)','Valorización','Rentabilidad total'],rows}}
 if(/TIR/.test(name)){const rows=[];pick('alt').forEach(p=>altMetrics(p).forEach(x=>rows.push([p,x.a.nombre,N(x.desemb),N(x.valor),N(x.distrib),N(x.moic),P(x.tir)])));return {heads:['Portafolio','Activo','Desembolsado','Valor actual','Distribuciones','MOIC','TIR (E.A.)'],rows}}
 const rows=[];pick('fvp').forEach(p=>{const s=perfStats(p,per,end);rows.push([p,P(s.rp),P(s.rb),pb(s.ex),P(s.vol),N(s.sharpe)])});return {heads:['Perfil (portafolio)','Rentabilidad','Benchmark','Exceso (pb)','Volatilidad','Sharpe'],rows}}
