/* =============== FASE 2 y 3 · Activos no listados, decisiones de inversión y FVP =============== */
function vehKind(n){return /^FONDO INMOBILIARIO/.test(n)?'inm':/^FONDO ALTERNATIVO/.test(n)?'alt':/^(FVP|APV)\b/.test(n)?'fvp':''}
function fvpFactor(n){return /CONSERVADOR/.test(n)?0.25:/MODERADO/.test(n)?1:/AGRESIVO/.test(n)?1.7:null}
const ASSET_CLASSES=['Renta fija','Inmueble','Proyecto','TCC','Cartera'];
function claseOf(r){return r.clase||'Renta fija'}
const D_=(y,m,d)=>new Date(y,m,d,12).getTime();
/* SUPUESTO: activos, avalúos, covenants y cifras de seguimiento son ilustrativos; los entrega Administración de activos y crédito. */
INSTRUMENTS.push(
 {mnem:'INM-001',clase:'Inmueble',nombre:'Torre empresarial Norte',tipo:'Oficinas',isin:'—',moneda:'COP',tasa:'',period:'',emi:D_(2021,3,10),ven:null,emisor:'Operador de servicios financieros',calif:'—',activo:true,port:'FONDO INMOBILIARIO 1',ciudad:'Bogotá',tipologia:'Oficinas',arrend:'Operador de servicios financieros',avaluos:[{valor:84500000000,fecha:D_(2026,2,15),avaluador:'Avaluadora Andina S.A.'},{valor:81200000000,fecha:D_(2025,2,10),avaluador:'Avaluadora Andina S.A.'}]},
 {mnem:'INM-002',clase:'Inmueble',nombre:'Bodega logística Occidente',tipo:'Logística',isin:'—',moneda:'COP',tasa:'',period:'',emi:D_(2022,8,5),ven:null,emisor:'Operador logístico regional',calif:'—',activo:true,port:'FONDO INMOBILIARIO 1',ciudad:'Medellín',tipologia:'Logística',arrend:'Operador logístico regional',avaluos:[{valor:46300000000,fecha:D_(2025,5,20),avaluador:'Tasaciones y Avalúos del Pacífico'}]},
 {mnem:'INM-003',clase:'Inmueble',nombre:'Centro comercial Plaza Mayor',tipo:'Comercial',isin:'—',moneda:'COP',tasa:'',period:'',emi:D_(2023,1,20),ven:null,emisor:'Cadena comercial líder',calif:'—',activo:true,port:'FONDO INMOBILIARIO 1',ciudad:'Barranquilla',tipologia:'Comercial',arrend:'Cadena comercial líder',avaluos:[{valor:62800000000,fecha:D_(2026,6,30),avaluador:'Consultores en Valoración Inmobiliaria'}]},
 {mnem:'PRY-001',clase:'Proyecto',nombre:'Proyecto vial Corredor Sur',tipo:'Infraestructura',isin:'—',moneda:'COP',tasa:'',period:'',emi:D_(2024,0,15),ven:D_(2031,5,30),emisor:'Constructora Andina',calif:'—',activo:true,port:'FONDO ALTERNATIVO 1',originador:'Constructora Andina',estructura:'Fiducia de administración y pagos',tramo:'Tramo preferente',sector:'Infraestructura',etapa:'Preoperativa',comp:40000000000,desemb:28000000000,flujoEsp:2600000000,val:{valor:31000000000,fecha:D_(2026,3,30),fuente:'Modelo de valoración del gestor'},covenants:[{n:'Cobertura de servicio de la deuda ≥ 1,20',estado:'Cumple'},{n:'Avance de obra ≥ 85 % del cronograma',estado:'Alerta'}]},
 {mnem:'PRY-002',clase:'Proyecto',nombre:'Proyecto de vivienda Altos del Parque',tipo:'Vivienda',isin:'—',moneda:'COP',tasa:'',period:'',emi:D_(2024,5,1),ven:D_(2028,11,15),emisor:'Promotora del Valle',calif:'—',activo:true,port:'FONDO ALTERNATIVO 1',originador:'Promotora del Valle',estructura:'Patrimonio autónomo',tramo:'Tramo único',sector:'Vivienda',etapa:'Operativa',comp:25000000000,desemb:25000000000,flujoEsp:3100000000,val:{valor:26200000000,fecha:D_(2026,5,30),fuente:'Modelo de valoración del gestor'},covenants:[{n:'Preventas ≥ 60 %',estado:'Cumple'}]},
 {mnem:'TCC-001',clase:'TCC',nombre:'TCC Cartera hipotecaria Serie A',tipo:'Titularización',isin:'XX0000000TCC',moneda:'COP',tasa:'9,2%',period:'MV',emi:D_(2024,9,1),ven:D_(2034,7,1),emisor:'Originadora de Crédito Andina',calif:'AAA',activo:true,port:'FONDO ALTERNATIVO 1',originador:'Originadora de Crédito Andina',estructura:'Titularización',tramo:'Serie A',sector:'Crédito hipotecario',etapa:'Operativa',comp:18000000000,desemb:18000000000,flujoEsp:1900000000,val:{valor:18500000000,fecha:D_(2026,8,30),fuente:'Precio del originador'},covenants:[{n:'Mora mayor a 90 días ≤ 4 %',estado:'Cumple'},{n:'Sobrecolateralización ≥ 110 %',estado:'Cumple'}]},
 {mnem:'CAR-001',clase:'Cartera',nombre:'Cartera de libranza Lote 12',tipo:'Libranza',isin:'—',moneda:'COP',tasa:'13,4%',period:'MV',emi:D_(2025,2,1),ven:D_(2030,2,1),emisor:'Originadora de Crédito Andina',calif:'AA',activo:true,port:'FONDO ALTERNATIVO 1',originador:'Originadora de Crédito Andina',estructura:'Compra de cartera',tramo:'Lote 12',sector:'Consumo',etapa:'Operativa',comp:9000000000,desemb:9000000000,flujoEsp:980000000,val:{valor:9000000000,fecha:D_(2026,6,30),fuente:'Modelo de valoración del gestor'},covenants:[{n:'Mora mayor a 60 días ≤ 6 %',estado:'Cumple'}]}
);
function assetVal(a){if(a.clase==='Inmueble'){const v=a.avaluos.slice().sort((x,y)=>y.fecha-x.fecha)[0];return {valor:v.valor,fecha:v.fecha,fuente:'Avalúo · '+v.avaluador}}return {valor:a.val.valor,fecha:a.val.fecha,fuente:a.val.fuente}}
const isValStale=f=>(fromIso(OPDATE)-f)/(30.4375*864e5)>PARAMS.valMonths;
function assetHoldings(name){const rows=INSTRUMENTS.filter(a=>a.clase&&a.clase!=='Renta fija'&&a.port===name);if(!rows.length)return null;
 return rows.map(a=>{const v=assetVal(a);return {macro:'ACTIVOS NO LISTADOS',sub:a.clase.toUpperCase(),moneda:a.moneda,plazo:a.ven?'MAYOR A 1,800':'SIN PLAZO',clase:a.clase.toUpperCase(),calif:a.calif,emisor:a.nombre,val:v.valor,ca:a.clase,fuente:v.fuente,fechaVal:v.fecha,vencida:isValStale(v.fecha)}})}
const valBadge=r=>r.vencida?badge('Valoración vencida','danger'):badge('Vigente','success');
/* Seguimiento de portafolios alternativos: comprometido frente a desembolsado, flujos esperados frente a reales y covenants */
function altTrack(host,port,op){const fac=dfac(op);
 const rows=INSTRUMENTS.filter(a=>a.port===port&&a.comp!=null).map(a=>{const rr=rng(hash(a.mnem+'tr')),exp=a.flujoEsp*fac,real=exp*(0.86+rr()*0.22),al=a.covenants.filter(c=>c.estado==='Alerta').length;return {n:a.nombre,mn:a.mnem,clase:a.clase,comp:a.comp*fac,desemb:a.desemb*fac,pend:(a.comp-a.desemb)*fac,pct:a.desemb/a.comp,exp,real,dev:real/exp-1,al,nc:a.covenants.length,cov:a.covenants}});
 const S1=f=>rows.reduce((a,x)=>a+f(x),0),comp=S1(x=>x.comp),des=S1(x=>x.desemb),ex=S1(x=>x.exp),re=S1(x=>x.real),al=S1(x=>x.al);
 host.innerHTML='<div class="mk-mb">'+srcChip('adminactivos')+'</div><div class="mk-kpis">'+kpiBox('Comprometido',f0(comp),'p','Monto comprometido en los proyectos y activos del portafolio')+kpiBox('Desembolsado',f0(des),'b')+kpiBox('% desembolsado','<span class="pos">'+pct(comp?des/comp:0,1)+'</span>','g','Desembolsado dividido por comprometido')+kpiBox('Flujos reales vs esperados',pct(ex?re/ex:0,1),'y','Flujos recibidos frente a los esperados a la fecha')+kpiBox('Covenants en alerta',String(al),al?'r':'g','Covenants cuyo indicador se acerca al límite pactado')+'</div><div id="tr"></div>';
 DataTable($('#tr',host),{cols:[{h:'Activo',k:'n',sortable:true},{h:'Clase',k:'clase'},{h:'Comprometido',k:'comp',fmt:f0},{h:'Desembolsado',k:'desemb',fmt:f0},{h:'Pendiente',k:'pend',fmt:f0},{h:'% desembolsado',k:'pct',fmt:v=>pct(v,1)},{h:'Flujo esperado',k:'exp',fmt:f0},{h:'Flujo real',k:'real',fmt:f0},{h:'Desviación',k:'dev',html:x=>valC(x.dev,(x.dev>=0?'+':'')+pct(x.dev,1)),txt:x=>pct(x.dev,1)},{h:'Covenants',k:'al',html:x=>x.al?badge(x.al+' de '+x.nc+' en alerta','warning'):badge('Cumplen','success'),txt:x=>x.al?x.al+' de '+x.nc+' en alerta':'Cumplen'}],rows:()=>rows,acts:()=>[['ver']],onAct:(a,x)=>{const m=openModal({title:'Covenants · '+x.n,body:'<div class="mk-tablewrap"><table class="mk-table"><thead><tr><th>Covenant</th><th>Estado</th></tr></thead><tbody>'+x.cov.map(c=>'<tr><td>'+esc(c.n)+'</td><td>'+badge(c.estado,c.estado==='Cumple'?'success':'warning')+'</td></tr>').join('')+'</tbody></table></div>',foot:'<button class="mk-btn mk-btn--secondary" data-c>Cerrar</button>'});$('[data-c]',m.el).addEventListener('click',m.close)},searchPh:'Activo...',fileName:'seguimiento-alternativos',noun:'activos',totals:rs=>['Total','',f0(comp),f0(des),f0(comp-des),pct(comp?des/comp:0,1),f0(ex),f0(re),'','']})}
/* Detalle de activos no listados (instrumentos) */
function assetDetail(r){const v=assetVal(r),rows=[['Código',esc(r.mnem)],['Clase de activo',r.clase],['Nombre',esc(r.nombre)],['Portafolio',esc(r.port)],['Valor vigente',money(v.valor)],['Fuente de la valoración',esc(v.fuente)],['Fecha de la valoración',fmtD(v.fecha)],['Estado de la valoración',isValStale(v.fecha)?'Valoración vencida':'Vigente']];
 if(r.clase==='Inmueble')rows.push(['Ciudad',esc(r.ciudad)],['Tipología',esc(r.tipologia)],['Arrendatario principal',esc(r.arrend)]);
 else rows.push(['Originador',esc(r.originador)],['Estructura',esc(r.estructura)],['Tramo',esc(r.tramo)],['Vencimiento',r.ven?fmtD(r.ven):'—'],['Sector',esc(r.sector)],['Etapa',esc(r.etapa)]);
 return rows}
function assetExtra(r){if(!r.clase||r.clase==='Renta fija')return '';
 if(r.clase==='Inmueble')return '<div class="mk-subhead mk-mt">'+ic('doc')+'Avalúos</div><div class="mk-tablewrap"><table class="mk-table"><thead><tr><th>Fecha</th><th>Valor</th><th>Avaluador</th></tr></thead><tbody>'+r.avaluos.slice().sort((a,b)=>b.fecha-a.fecha).map(a=>'<tr><td>'+fmtD(a.fecha)+'</td><td>'+money(a.valor)+'</td><td>'+esc(a.avaluador)+'</td></tr>').join('')+'</tbody></table></div><div class="mk-mt"><button type="button" class="mk-btn" data-av>'+ic('plus')+'Registrar avalúo</button></div>';
 return '<div class="mk-subhead mk-mt">'+ic('limits')+'Covenants</div><div class="mk-tablewrap"><table class="mk-table"><thead><tr><th>Covenant</th><th>Estado</th></tr></thead><tbody>'+r.covenants.map(c=>'<tr><td>'+esc(c.n)+'</td><td>'+badge(c.estado,c.estado==='Cumple'?'success':'warning')+'</td></tr>').join('')+'</tbody></table></div>'}
function assetBind(el,r,rp){const b=$('[data-av]',el);if(!b)return;b.addEventListener('click',()=>{const m=openModal({z:80,title:'Registrar avalúo · '+r.mnem,sub:'El avalúo queda en el historial; el valor vigente es el más reciente.',body:'<div class="mk-formgrid">'+inpF('av-v','Valor del avalúo',"",{req:true,ph:'Ej: 90000000000'})+dateF('av-f','Fecha del avalúo',fromIso(OPDATE),{req:true})+selF('av-a','Avaluador',AVALUADORES,AVALUADORES[0],{req:true})+'</div>',foot:'<button class="mk-btn mk-btn--secondary" data-c>Cancelar</button><button class="mk-btn" data-ok>'+ic('save')+'Guardar</button>'});
 $('[data-c]',m.el).addEventListener('click',m.close);
 $('[data-ok]',m.el).addEventListener('click',()=>{const v=okNum($('[name=av-v]',m.el).value),f=fromIso($('[name=av-f]',m.el).value),a=$('[name=av-a]',m.el).value;let bad=false;if(!(v>0)){errOn(m.el,'av-v','Ingresa el valor');bad=true}if(!f){errOn(m.el,'av-f','Indica la fecha');bad=true}if(!a){errOn(m.el,'av-a','Selecciona el avaluador');bad=true}if(bad)return;
  r.avaluos.push({valor:v,fecha:f,avaluador:a});publishEvent('Avalúo registrado',r.mnem,r.nombre+' · '+money(v)+' · '+a,'contabilidad');m.close();$$('.mk-modal-overlay').forEach(x=>x.remove());rp&&rp();toast('Avalúo registrado. Se publicó el evento “Avalúo registrado”.','success','Avalúo registrado')})})}
const AVALUADORES=['Avaluadora Andina S.A.','Tasaciones y Avalúos del Pacífico','Consultores en Valoración Inmobiliaria'];
/* Formulario de activos no listados */
function assetForm(row,rp){
 const cl=row?row.clase:'Inmueble',inm=cl==='Inmueble';
 const m=openModal({brand:true,cls:'mk-modal--form',title:(row?'Editar ':'Nuevo ')+'activo no listado',sticky:true,body:'<form novalidate><div class="mk-formgrid">'+selF('clase','Clase de activo',['Inmueble','Proyecto','TCC','Cartera'],cl,{req:true})+inpF('mnem','Código',row&&row.mnem,{req:true})+inpF('nombre','Nombre',row&&row.nombre,{req:true,cls:'span2'})+selF('port','Portafolio',FUNDS.filter(f=>vehKind(f)==='inm'||vehKind(f)==='alt'),row&&row.port,{req:true})+inpF('valor','Valor vigente',row?String(assetVal(row).valor):'',{req:true,ph:'Ej: 30000000000'})+inpF('fuente','Fuente de la valoración',row?assetVal(row).fuente:'Modelo de valoración del gestor')+'<div data-g="Inmueble" class="span3"><div class="mk-formgrid">'+inpF('ciudad','Ciudad',row&&row.ciudad)+inpF('tipologia','Tipología',row&&row.tipologia)+inpF('arrend','Arrendatario principal',row&&row.arrend)+'</div></div><div data-g="otros" class="span3"><div class="mk-formgrid">'+inpF('originador','Originador',row&&row.originador)+inpF('estructura','Estructura',row&&row.estructura)+inpF('tramo','Tramo',row&&row.tramo)+inpF('sector','Sector',row&&row.sector)+selF('etapa','Etapa',['Preoperativa','Operativa'],row&&row.etapa)+dateF('ven','Vencimiento',row&&row.ven)+'</div></div></div></form>',foot:'<button class="mk-btn mk-btn--secondary" data-c>Cancelar</button><button class="mk-btn" data-s>'+ic('save')+'Guardar</button>'});
 const f=$('form',m.el);bindClear(f);const sync=()=>{const i=$('[name=clase]',f).value==='Inmueble';$('[data-g="Inmueble"]',f).hidden=!i;$('[data-g="otros"]',f).hidden=i};$('[name=clase]',f).addEventListener('change',sync);sync();
 $('[data-c]',m.el).addEventListener('click',m.close);
 $('[data-s]',m.el).addEventListener('click',()=>{const g=n=>$('[name="'+n+'"]',f).value.trim(),errs=[];const mn=g('mnem'),c=g('clase'),val=okNum(g('valor'));
  if(!mn)errs.push(['mnem','Indica el código','Código']);else if(INSTRUMENTS.some(i=>i!==row&&normH(i.mnem)===normH(mn)))errs.push(['mnem','Ya existe un instrumento con ese código','Código']);
  if(!g('nombre'))errs.push(['nombre','Indica el nombre','Nombre']);if(!g('port'))errs.push(['port','Selecciona el portafolio','Portafolio']);if(!(val>0))errs.push(['valor','El valor debe ser mayor a 0','Valor']);
  if(errs.length){errs.forEach(e=>errOn(f,e[0],e[1]));toast('Completa: '+errs.map(e=>e[2]).join(', ')+'.','warning','Faltan datos');return}
  const base={mnem:mn,clase:c,nombre:g('nombre'),port:g('port'),moneda:MONEDAS()[0],isin:'—',tasa:'',period:'',emi:row?row.emi:fromIso(OPDATE),activo:row?row.activo:true,calif:'—'};
  let o;if(c==='Inmueble')o=Object.assign(base,{tipo:g('tipologia')||'Inmueble',ven:null,emisor:g('arrend'),ciudad:g('ciudad'),tipologia:g('tipologia'),arrend:g('arrend'),avaluos:row&&row.avaluos?row.avaluos:[{valor:val,fecha:fromIso(OPDATE),avaluador:AVALUADORES[0]}]});
  else o=Object.assign(base,{tipo:g('estructura')||c,ven:fromIso(g('ven')),emisor:g('originador'),originador:g('originador'),estructura:g('estructura'),tramo:g('tramo'),sector:g('sector'),etapa:g('etapa')||'Preoperativa',comp:row&&row.comp?row.comp:val,desemb:row&&row.desemb?row.desemb:0,flujoEsp:row&&row.flujoEsp?row.flujoEsp:0,val:{valor:val,fecha:fromIso(OPDATE),fuente:g('fuente')||'Modelo de valoración del gestor'},covenants:row&&row.covenants?row.covenants:[]});
  if(row)Object.keys(row).forEach(k=>delete row[k]);if(row)Object.assign(row,o);else INSTRUMENTS.push(o);
  m.close();rp&&rp();toast('Activo '+(row?'actualizado':'creado')+' correctamente.','success',row?'Cambios guardados':'Registro creado')})
}
/* Régimen de inversión del FVP, versionado con fecha de vigencia. SUPUESTO: topes ilustrativos por perfil, a ajustar por el negocio. */
const FVP_PERFILES=['Conservador','Moderado','Agresivo'];
const FVP_REG=[
 {ver:1,desde:D_(2025,0,2),p:{Conservador:{rvMax:10,rfMin:70,extMax:10,emiMax:10},Moderado:{rvMax:30,rfMin:50,extMax:20,emiMax:10},Agresivo:{rvMax:45,rfMin:30,extMax:30,emiMax:12}}},
 {ver:2,desde:D_(2026,3,1),p:{Conservador:{rvMax:12,rfMin:70,extMax:10,emiMax:10},Moderado:{rvMax:32,rfMin:50,extMax:20,emiMax:10},Agresivo:{rvMax:45,rfMin:30,extMax:30,emiMax:12}}}
];
const regVigente=()=>FVP_REG.filter(v=>v.desde<=fromIso(OPDATE)).sort((a,b)=>b.desde-a.desde)[0]||FVP_REG[0];
const regState=v=>v===regVigente()?['Vigente','success']:v.desde>fromIso(OPDATE)?['Futura','info']:['Histórica','neutral'];
function regimenExtra(pg,rp){
 const x=document.createElement('div');x.className='mk-accordion collapsed mk-mt';x.id='regimen';
 x.innerHTML='<div class="mk-accordion__head"><span class="mk-accordion__ico">'+ic('limits')+'</span><span><span class="mk-accordion__t">'+loc('Régimen de inversión del FVP')+'</span><span class="mk-accordion__d">Parámetros por perfil de riesgo, versionados con fecha de vigencia</span></span><span class="mk-accordion__chev">&#9662;</span></div><div class="mk-accordion__body"><div class="mk-mb">'+badge('Por definir con el negocio','warning')+' <span class="mk-help">Topes ilustrativos; cada versión conserva el historial.</span></div><div style="display:flex;justify-content:flex-end" class="mk-mb"><button type="button" class="mk-btn" data-nv>'+ic('plus')+'Nueva versión</button></div><div id="rg"></div></div>';
 pg.appendChild(x);bindAcc(x);
 const draw=()=>DataTable($('#rg',x),{cols:[{h:'Versión',k:'ver',sortable:true},{h:'Vigente desde',k:'desde',fmt:fmtD,sortable:true},...FVP_PERFILES.map(p=>({h:p+' · tope RV / mín. RF',html:v=>v.p[p].rvMax+' % / '+v.p[p].rfMin+' %',txt:v=>v.p[p].rvMax+' % / '+v.p[p].rfMin+' %'}))],rows:()=>FVP_REG,acts:()=>[['ver']],estado:v=>{const s=regState(v);return badge(s[0],s[1],true)},noPage:true,noFilters:true,fileName:'regimen-inversion-fvp',noun:'versiones',defaultSort:'Versión',defaultDir:-1,
  onAct:(a,v)=>{const m=openModal({title:'Régimen de inversión · versión '+v.ver,sub:'Vigente desde '+fmtD(v.desde),body:'<div class="mk-tablewrap"><table class="mk-table"><thead><tr><th>Parámetro</th>'+FVP_PERFILES.map(p=>'<th>'+p+'</th>').join('')+'</tr></thead><tbody>'+[['Tope en renta variable (%)','rvMax'],['Mínimo en renta fija (%)','rfMin'],['Tope en el exterior (%)','extMax'],['Tope por emisor (%)','emiMax']].map(r=>'<tr><td>'+r[0]+'</td>'+FVP_PERFILES.map(p=>'<td>'+v.p[p][r[1]]+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>',foot:'<button class="mk-btn mk-btn--secondary" data-c>Cerrar</button>'});$('[data-c]',m.el).addEventListener('click',m.close)}});
 draw();
 $('[data-nv]',x).addEventListener('click',()=>{const cur=regVigente(),fields=[['rvMax','Tope RV (%)'],['rfMin','Mínimo RF (%)'],['extMax','Tope exterior (%)'],['emiMax','Tope por emisor (%)']];
  const m=openModal({brand:true,cls:'mk-modal--form',title:'Nueva versión del régimen',sub:'La versión anterior se conserva. Parte de la vigente.',sticky:true,body:'<form novalidate><div class="mk-formgrid">'+dateF('vig','Vigente desde',fromIso(OPDATE),{req:true})+'</div>'+FVP_PERFILES.map(p=>'<div class="mk-subhead mk-mt">'+p+'</div><div class="mk-formgrid">'+fields.map(f=>inpF(p+'-'+f[0],f[1],String(cur.p[p][f[0]]),{req:true})).join('')+'</div>').join('')+'</form>',foot:'<button class="mk-btn mk-btn--secondary" data-c>Cancelar</button><button class="mk-btn" data-s>'+ic('save')+'Guardar versión</button>'});
  const f=$('form',m.el);bindClear(f);$('[data-c]',m.el).addEventListener('click',m.close);
  $('[data-s]',m.el).addEventListener('click',()=>{const vig=fromIso($('[name=vig]',f).value),errs=[],p={};
   if(!vig)errs.push(['vig','Indica la fecha de vigencia']);else if(FVP_REG.some(v=>v.desde===vig))errs.push(['vig','Ya existe una versión con esa fecha']);
   FVP_PERFILES.forEach(pf=>{p[pf]={};fields.forEach(fl=>{const n=pf+'-'+fl[0],v=okNum($('[name="'+n+'"]',f).value);if(!(v>=0&&v<=100))errs.push([n,'Entre 0 y 100']);p[pf][fl[0]]=v})});
   if(errs.length){errs.forEach(e=>errOn(f,e[0],e[1]));toast('Revisa los campos marcados.','warning','Faltan datos');return}
   FVP_REG.push({ver:Math.max.apply(null,FVP_REG.map(v=>v.ver))+1,desde:vig,p});m.close();draw();toast('Versión del régimen guardada; la anterior se conserva.','success','Régimen actualizado')})});
}
/* Decisiones de inversión: activos sin orden de mercado */
const DEC_TIPOS=['Compra de inmueble','Venta de inmueble','Desembolso a proyecto','Compra de cartera'];
const DEC_STATES=['Propuesta','En comité','Aprobada','Rechazada'];
const DST2={'Propuesta':'info','En comité':'warning','Aprobada':'success','Rechazada':'danger'};
const decEst=r=>badge(r.estado,DST2[r.estado],true);
const DEC_ORDERS=[
 ['DI-0001','Compra de inmueble','INM-003','FONDO INMOBILIARIO 1',62800000000,'Laura Medina',['Camilo Ortega','Paula Rincón'],'ACTA-2026-014','Aprobada',[2026,6,10]],
 ['DI-0002','Desembolso a proyecto','PRY-001','FONDO ALTERNATIVO 1',5000000000,'Camilo Ortega',['Laura Medina','Paula Rincón'],'ACTA-2026-021','En comité',[2026,8,24]],
 ['DI-0003','Compra de cartera','CAR-001','FONDO ALTERNATIVO 1',8000000000,'Paula Rincón',['Laura Medina','Camilo Ortega'],'','Propuesta',[2026,8,29]],
 ['DI-0004','Venta de inmueble','INM-002','FONDO INMOBILIARIO 1',35000000000,'Laura Medina',['Camilo Ortega','Ramiro Giraldo Colorado'],'ACTA-2026-018','Rechazada',[2026,7,18]],
 ['DI-0005','Desembolso a proyecto','PRY-002','FONDO ALTERNATIVO 1',3000000000,'Paula Rincón',['Ramiro Giraldo Colorado','Camilo Ortega'],'ACTA-2026-016','Aprobada',[2026,7,5]]
].map(a=>({id:a[0],tipo:a[1],activo:a[2],port:a[3],monto:a[4],prop:a[5],aprob:a[6],acta:a[7],estado:a[8],fecha:D_(a[9][0],a[9][1],a[9][2]),motivo:a[8]==='Rechazada'?'El comité considera excesiva la concentración en un solo inmueble.':''}));
const DEC_ACTAS=[{dec:'DI-0001',ver:1,acta:'ACTA-2026-014',aprob:'Camilo Ortega',monto:62800000000,fecha:D_(2026,6,12),nota:''},{dec:'DI-0005',ver:1,acta:'ACTA-2026-016',aprob:'Ramiro Giraldo Colorado',monto:3000000000,fecha:D_(2026,7,8),nota:''}];
const assetOf=mn=>INSTRUMENTS.find(i=>i.mnem===mn);
const decAssets=tipo=>INSTRUMENTS.filter(a=>a.clase&&a.clase!=='Renta fija'&&(tipo==='Compra de inmueble'||tipo==='Venta de inmueble'?a.clase==='Inmueble':tipo==='Compra de cartera'?a.clase==='Cartera':(a.clase==='Proyecto'||a.clase==='TCC'))&&a.activo);
const decPorts=()=>FUNDS.filter(f=>vehKind(f)==='inm'||vehKind(f)==='alt');
/* Validación previa de concentración. SUPUESTO: la concentración por inmueble o proyecto es un límite interno. */
function concCheck(d){const a=assetOf(d.activo),h=holdingsFor(d.port),tot=h.reduce((s,x)=>s+x.val,0),add=/Compra|Desembolso/.test(d.tipo)?d.monto:-d.monto,cur=a&&a.port===d.port?assetVal(a).valor:0,share=(cur+add)/(tot+add);
 const tp=a&&a.clase==='Inmueble'?'CONCENTRACIÓN POR INMUEBLE':'CONCENTRACIÓN POR PROYECTO',lim=LIMITS.find(l=>l.activo&&l.port===d.port&&l.tipo===tp&&l.sub===d.activo)||LIMITS.find(l=>l.activo&&l.port===d.port&&l.tipo===tp);
 return {share,tipo:tp,lim:lim?lim.pct:null,nat:lim?natOf(lim):'Interno',estado:lim?(share>lim.pct?'Excedido':share>=lim.pct*0.9?'Alerta':'Cumple'):'Sin límite configurado'}}
const decAct=d=>{const a=[['ver']];if(d.estado==='Propuesta'){a.push(['edit']);a.push(['send']);}if(d.estado==='En comité'){a.push(['apr']);a.push(['rej'])}if(d.estado==='Aprobada')a.push(['fixa']);return a};
AI.send=['','flows','Enviar a comité'];AI.apr=['mk-iconbtn--ok','check','Aprobar'];AI.rej=['mk-iconbtn--delete','x','Rechazar'];AI.fixa=['','pen','Corregir acta'];
function decActas(id){return DEC_ACTAS.filter(a=>a.dec===id).sort((a,b)=>b.ver-a.ver)}
PAGES.idec=crudPage({title:'Decisiones de inversión',help:'Compra y venta de inmuebles, desembolsos a proyectos y compra de cartera: propuesta, comité y acta de aprobación.',newLabel:'Nueva decisión',apoya:APO.idec,dateRange:{k:'fecha',label:'fecha de la propuesta'},entity:'decisión de inversión',entityArt:'La decisión',fileName:'decisiones-inversion',defaultSort:'Creada',defaultDir:-1,searchPh:'N° de decisión, activo o portafolio...',noun:'decisiones',
 filters:[{id:'tipo',label:'Tipo',opts:()=>DEC_TIPOS,get:r=>r.tipo},{id:'port',label:'Portafolio',opts:()=>decPorts(),get:r=>r.port},{id:'est',label:'Estado',opts:()=>DEC_STATES,get:r=>r.estado}],
 kpis:rows=>DEC_STATES.map((s,i)=>[s==='En comité'?'En comité':s+'s',rows.filter(r=>r.estado===s).length,['b','y','g','r'][i]]),
 cols:[{h:'N° decisión',k:'id',sortable:true},{h:'Tipo',k:'tipo'},{h:'Activo',k:'activo',html:r=>{const a=assetOf(r.activo);return esc(r.activo)+(a?' · '+esc(a.nombre):'')},txt:r=>{const a=assetOf(r.activo);return r.activo+(a?' · '+a.nombre:'')}},{h:'Portafolio',k:'port'},{h:'Monto',k:'monto',fmt:f0},{h:'Proponente',k:'prop'},{h:'N° de acta',k:'acta',fmt:v=>v||'—'},{h:'Creada',k:'fecha',fmt:dstr,sortable:true}],
 rows:()=>DEC_ORDERS,estado:decEst,acts:decAct,
 detail:r=>[['N° de decisión',r.id],['Tipo',r.tipo],['Activo',esc(r.activo+(assetOf(r.activo)?' · '+assetOf(r.activo).nombre:''))],['Portafolio',esc(r.port)],['Monto',money(r.monto)],['Proponente',esc(r.prop)],['Aprobadores',esc(r.aprob.join(', '))],['N° de acta',esc(r.acta||'—')],['Creada',dstr(r.fecha)],['Estado',r.estado]].concat(r.motivo?[['Motivo del rechazo',esc(r.motivo)]]:[]),badges:r=>decEst(r),detailTitle:r=>'Decisión · '+r.id,
 detailExtra:r=>{const v=decActas(r.id);return v.length?'<div class="mk-subhead mk-mt">'+ic('doc')+'Acta de aprobación (inmutable)</div><div class="mk-tablewrap"><table class="mk-table"><thead><tr><th>Versión</th><th>Acta</th><th>Aprobó</th><th>Monto</th><th>Fecha</th><th>Nota</th></tr></thead><tbody>'+v.map(a=>'<tr><td>'+a.ver+'</td><td>'+esc(a.acta)+'</td><td>'+esc(a.aprob)+'</td><td>'+money(a.monto)+'</td><td>'+fmtD(a.fecha)+'</td><td>'+esc(a.nota||'—')+'</td></tr>').join('')+'</tbody></table></div>':''},
 form:row=>({html:'<div class="mk-formgrid">'+selF('tipo','Tipo de decisión',DEC_TIPOS,row&&row.tipo,{req:true})+selF('activo','Activo',row?decAssets(row.tipo).map(a=>a.mnem):[],row&&row.activo,{req:true,tip:'Precargado desde Administración de activos y crédito.'})+selF('port','Portafolio',decPorts(),row&&row.port,{req:true})+inpF('monto','Monto',row?String(row.monto):'',{req:true,ph:'Ej: 5000000000'})+fld('Proponente','<input class="mk-input" name="prop" value="'+esc(row?row.prop:USER.name)+'" readonly>',{name:'prop',tip:'Quien propone no puede aprobar.'})+selF('ap1','Aprobador 1',USERS.filter(u=>u!==(row?row.prop:USER.name)),row&&row.aprob[0],{req:true})+selF('ap2','Aprobador 2',USERS.filter(u=>u!==(row?row.prop:USER.name)),row&&row.aprob[1],{req:true})+inpF('acta','N° de acta',row&&row.acta,{ph:'Se exige para aprobar'})+'</div><div class="mk-help mk-mt" id="ainfo"></div><div class="mk-mt">'+srcChip('adminactivos')+'</div>',
  bind:f=>{const up=()=>{const a=assetOf($('[name=activo]',f).value);$('#ainfo',f).innerHTML=a?'<b>'+esc(a.nombre)+'</b> · '+esc(a.clase)+' · valor vigente '+money(assetVal(a).valor)+' · '+esc(assetVal(a).fuente)+' al '+fmtD(assetVal(a).fecha):'Elige el tipo y el activo para ver su valoración.'};$('[name=tipo]',f).addEventListener('change',e=>{const s=$('[name=activo]',f);s.innerHTML='<option value="">Seleccionar</option>'+decAssets(e.target.value).map(a=>'<option value="'+esc(a.mnem)+'">'+esc(a.mnem)+' · '+esc(a.nombre)+'</option>').join('');up()});$('[name=activo]',f).addEventListener('change',up);up()},
  read:f=>{const g=n=>$('[name="'+n+'"]',f).value.trim(),errs=[],mo=okNum(g('monto'));['tipo','activo','port','ap1','ap2'].forEach(n=>{if(!g(n))errs.push([n,'Selecciona una opción',n])});if(!(mo>0))errs.push(['monto','El monto debe ser mayor a 0','Monto']);if(g('ap1')&&g('ap1')===g('ap2'))errs.push(['ap2','Los aprobadores deben ser distintos','Aprobador 2']);if(errs.length)return {ok:false,errs};return {ok:true,data:{tipo:g('tipo'),activo:g('activo'),port:g('port'),monto:mo,prop:g('prop'),aprob:[g('ap1'),g('ap2')],acta:g('acta')}}}}),
 review:d=>[['Tipo',d.tipo],['Activo',d.activo],['Portafolio',d.port],['Monto',money(d.monto)],['Proponente',d.prop],['Aprobadores',d.aprob.join(', ')],['N° de acta',d.acta||'—']],
 onSave:(o,row)=>{if(row)Object.assign(row,o);else DEC_ORDERS.unshift(Object.assign({id:nextId('DI',DEC_ORDERS),estado:'Propuesta',fecha:Date.now(),motivo:''},o))},
 onAct:(a,d,rp)=>{
  if(a==='send'){const c=concCheck(d),m=openModal({title:'Validación previa de límites',sub:'Antes de enviar a comité se revisa la concentración.',body:'<div class="mk-tablewrap"><table class="mk-table"><thead><tr><th>Límite</th><th>Naturaleza</th><th>Participación con la decisión</th><th>Límite</th><th>Resultado</th></tr></thead><tbody><tr><td>'+esc(c.tipo)+'</td><td>'+natB(c.nat)+'</td><td>'+pct(c.share,1)+'</td><td>'+(c.lim!=null?pct(c.lim,1):'—')+'</td><td>'+(c.estado==='Excedido'?estB('Excedido'):c.estado==='Alerta'?estB('Alerta'):c.estado==='Cumple'?estB('Cumple'):esc(c.estado))+'</td></tr></tbody></table></div>'+(c.estado==='Excedido'?'<div class="mk-mt">'+alertB('warning','Límite interno excedido','Puede continuar: el comité verá la concentración y decidirá. Queda registrado el evento.')+'</div>':''),foot:'<button class="mk-btn mk-btn--secondary" data-c>Cancelar</button><button class="mk-btn" data-ok>Enviar a comité</button>'});
   $('[data-c]',m.el).addEventListener('click',m.close);$('[data-ok]',m.el).addEventListener('click',()=>{if(c.estado==='Excedido'&&c.nat==='Normativo'){toast('Límite normativo excedido: no se puede enviar a comité.','danger','Decisión bloqueada');return}if(c.estado==='Excedido')publishEvent('Límite excedido',d.id,c.tipo+' ('+c.nat+'): participación '+pct(c.share,1)+' sobre un límite de '+pct(c.lim,1),'cumplimiento');d.estado='En comité';m.close();rp();toast('La decisión '+d.id+' pasó a comité.','success','Enviada a comité')})}
  else if(a==='apr'||a==='rej'){const ap=a==='apr',opts=d.aprob.filter(u=>u!==d.prop),m=openModal({title:(ap?'Aprobar':'Rechazar')+' decisión '+d.id,sub:'Segregación de funciones: el aprobador no puede ser el proponente ('+d.prop+').',body:'<div class="mk-formgrid">'+fld('Aprobador','<div class="mk-combobox"><select class="mk-select" name="ua"><option value="">Seleccionar</option>'+opts.map(u=>'<option>'+esc(u)+'</option>').join('')+'</select></div>',{req:true,name:'ua'})+(ap?inpF('acta','N° de acta',d.acta,{req:true}):fld('Motivo del rechazo','<textarea class="mk-input" name="mot" rows="3"></textarea>',{req:true,name:'mot'}))+'</div>',foot:'<button class="mk-btn mk-btn--secondary" data-c>Cancelar</button><button class="mk-btn'+(ap?'':' mk-btn--danger')+'" data-ok>'+ic(ap?'check':'x')+(ap?'Aprobar':'Rechazar')+'</button>'});
   $('[data-c]',m.el).addEventListener('click',m.close);
   $('[data-ok]',m.el).addEventListener('click',()=>{const u=$('[name=ua]',m.el).value;let bad=false;if(!u){errOn(m.el,'ua','Selecciona el aprobador');bad=true}else if(u===d.prop){errOn(m.el,'ua','El aprobador no puede ser el proponente');bad=true}
    if(ap){const ac=$('[name=acta]',m.el).value.trim();if(!ac){errOn(m.el,'acta','El número de acta es obligatorio');bad=true}if(bad)return;d.acta=ac;d.estado='Aprobada';DEC_ACTAS.push({dec:d.id,ver:1,acta:ac,aprob:u,monto:d.monto,fecha:Date.now(),nota:''});publishEvent('Decisión aprobada',d.id,d.tipo+' · '+d.activo+' · '+money(d.monto)+' · '+ac,'contabilidad');toast('Decisión aprobada. El acta quedó inmutable y se publicó el evento “Decisión aprobada”.','success','Decisión aprobada')}
    else{const mt=$('[name=mot]',m.el).value.trim();if(!mt){errOn(m.el,'mot','Indica el motivo');bad=true}if(bad)return;d.estado='Rechazada';d.motivo=mt;toast('Decisión rechazada.','warning','Decisión rechazada')}
    m.close();rp()})}
  else if(a==='fixa'){const v=decActas(d.id)[0],m=openModal({title:'Corregir el acta de '+d.id,sub:'El acta aprobada no se edita: se crea la versión '+(v.ver+1)+' y se conserva la anterior.',body:'<div class="mk-formgrid">'+inpF('acta','N° de acta',v.acta,{req:true})+inpF('monto','Monto',String(v.monto),{req:true})+fld('Motivo de la corrección','<textarea class="mk-input" name="mot" rows="3"></textarea>',{req:true,name:'mot'})+'</div>',foot:'<button class="mk-btn mk-btn--secondary" data-c>Cancelar</button><button class="mk-btn" data-ok>'+ic('save')+'Guardar versión '+(v.ver+1)+'</button>'});
   $('[data-c]',m.el).addEventListener('click',m.close);
   $('[data-ok]',m.el).addEventListener('click',()=>{const ac=$('[name=acta]',m.el).value.trim(),mo=okNum($('[name=monto]',m.el).value),mt=$('[name=mot]',m.el).value.trim();let bad=false;if(!ac){errOn(m.el,'acta','Indica el acta');bad=true}if(!(mo>0)){errOn(m.el,'monto','El monto debe ser mayor a 0');bad=true}if(!mt){errOn(m.el,'mot','Indica el motivo');bad=true}if(bad)return;DEC_ACTAS.push({dec:d.id,ver:v.ver+1,acta:ac,aprob:v.aprob,monto:mo,fecha:Date.now(),nota:mt});d.acta=ac;d.monto=mo;m.close();rp();toast('Se creó la versión '+(v.ver+1)+' del acta; la anterior se conserva.','success','Acta corregida')})}
 }
});
