const fs=require('fs');let s=fs.readFileSync('mk.before_panama.js','utf8');
const rep=(a,b)=>{if(!s.includes(a))throw new Error('missing: '+a.slice(0,80));s=s.replace(a,()=>b)};
const M=[['BANCO POPULAR S.A.','BAC PANAMÁ'],['BANCO AV VILLAS','BANCO ALIADO'],['SCOTIABANK COLPATRIA','SCOTIABANK PANAMÁ'],['CORFICOLOMBIANA','PRIVAL SECURITIES'],['BANCO COOMEVA','CAJA DE AHORROS'],['SIMULTÁNEAS','REPOS'],['SIMULTÁNEA','REPO'],['Simultánea','Repo'],['TES CORTO','LETRA DEL TESORO CORTO'],['IBR OVERNIGHT','SOFR OVERNIGHT'],['TASA DE REPO BANREP','TASA FED FUNDS'],['Indicador Bancario de Referencia a 1 día','Secured Overnight Financing Rate a 1 día'],['Comisionista','Casa de valores'],
['MINISTERIO DE HACIENDA (TES)','MINISTERIO DE ECONOMÍA Y FINANZAS (TESORO)'],['BANCO DE LA REPÚBLICA','BANCO NACIONAL DE PANAMÁ'],['FIDUCIARIA BANCOLOMBIA','BG INVESTMENTS'],['BANCOLOMBIA S.A.','BANCO GENERAL'],['BANCO DAVIVIENDA','BANISTMO'],['BANCO DE BOGOTÁ','GLOBAL BANK'],['ECOPETROL S.A.','COPA HOLDINGS'],['ISA S.A. E.S.P.','ENSA'],['GRUPO SURA','GRUPO ASSA'],['TITULARIZADORA COLOMBIANA','MULTIBANK'],['FINDETER','BANCO HIPOTECARIO NACIONAL'],['COLPENSIONES','CAJA DE SEGURO SOCIAL'],['CEMENTOS ARGOS','CEMENTO PANAMÁ'],['Bolsa de Valores de Colombia','Bolsa de Valores de Panamá'],['Banco de la República','Banco Nacional de Panamá'],['DANE','INEC'],['Índice de TES de corto plazo','Índice de letras del Tesoro de corto plazo'],['Índice de TES de largo plazo','Índice de bonos del Tesoro de largo plazo'],['Índice TES Corto','Índice Letras Tesoro Corto'],['Índice TES Largo','Índice Bonos Tesoro Largo'],['de TES','de letras y bonos del Tesoro'],['Índice de capitalización bursátil','Índice bursátil de la Bolsa de Valores de Panamá'],['COLCAP','Índice BVP'],['Indicador Bancario de Referencia a 1 mes','Secured Overnight Financing Rate a 1 mes'],['Indicador Bancario de Referencia a 3 meses','Secured Overnight Financing Rate a 3 meses'],['Depósito a Término Fijo a 90 días','Tasa de depósitos a plazo fijo a 90 días'],['IBR 1M','SOFR 1M'],['IBR 3M','SOFR 3M'],['DTF 90D','TASA DPF 90D'],['Benchmark FIC','Benchmark Fondo'],['FIC ','FONDO DE INVERSIÓN '],['"FIC"','"Fondo de inversión"'],['"IBR"','"SOFR"'],['"DTF"','"TASA DPF"'],['"UVR"','"USD"'],['"COP"','"PAB"'],['TFIT','LTES'],['CDT','DPF'],['ECOPETROL','COPA'],['CELSIA','ELEKTRA'],['CEMARGOS','CEMPAN'],['BOGOTA','GLOBAL'],['BSANTANDER','BGENERAL'],['BVC','BVPA'],['Colombia','Panamá']];
const block=",
 'Panamá':{
  m:"+JSON.stringify(M)+",
  ex:{FIC:'Fondo de inversión',IBR:'SOFR',UVR:'USD',DTF:'TASA DPF',COP:'PAB','Cédula de Ciudadanía':'Cédula de identidad personal',NIT:'RUC','Cédula de Extranjería':'Carné de residente permanente'},
  fix:()=>{const ok=TIPOS_P['Panamá'];INSTRUMENTS.forEach(r=>{if(!ok.includes(r.tipo))r.tipo='TASA FIJA'});LEVELS.Moneda=['PAB','USD','EUR'];SUBLIMITS.MONEDA=['PAB','USD','EUR'];HOLDINGS_BASE.forEach(h=>{if(/LOCAL/.test(h[1])&&h[2]==='USD')h[2]='PAB'})}
 }";
rep("\n }\n};\nfunction mapStr","\n }"+block+"\n};\nfunction mapStr");
/* catálogos por país */
rep("'República Dominicana':[['DOP','Peso dominicano','Moneda base']","'Panamá':[['PAB','Balboa panameño','Moneda base (a la par con el dólar)'],['USD','Dólar estadounidense','Moneda de circulación'],['EUR','Euro','Inversiones internacionales']],\n 'República Dominicana':[['DOP','Peso dominicano','Moneda base']");
rep("'República Dominicana':['DESCUENTO','TASA REFERENCIA'","'Panamá':['DESCUENTO','SOFR','TASA FIJA','TASA VARIABLE','TASA DPF','CUPÓN CERO'],'República Dominicana':['DESCUENTO','TASA REFERENCIA'");
rep("'República Dominicana':['DOP','USD','EUR']};","'República Dominicana':['DOP','USD','EUR'],'Panamá':['PAB','USD','EUR']};");
rep("<option>República Dominicana</option>","<option>República Dominicana</option><option>Panamá</option>");
fs.writeFileSync('mk.js',s);console.log('ok');
