const fs=require('fs');let s=fs.readFileSync('mk.js','utf8');
if(!fs.existsSync('mk.before26.js'))fs.writeFileSync('mk.before26.js',s);
s=fs.readFileSync('mk.before26.js','utf8');
const rep=(a,b)=>{if(!s.includes(a))throw new Error('missing: '+a.slice(0,110));s=s.replace(a,()=>b)};
const slice=(from,to,ins)=>{const i=s.indexOf(from),j=s.indexOf(to);if(i<0||j<0||j<i)throw new Error('slice '+from.slice(0,40));s=s.slice(0,i)+ins+s.slice(j)};

/* 1) Exportes y libros .xlsx reales */
slice('const colL=i=>','async function inflateRaw',fs.readFileSync('ins_export.js','utf8')+'\n');
/* 2) Exportes de las tablas: CSV y Excel con los datos tal como se ven */
slice("$$('[data-x]',host).forEach(b=>b.addEventListener('click',()=>{const a=filtered()","$$('[data-act]',host).forEach",
"$$('[data-x]',host).forEach(b=>b.addEventListener('click',()=>{const a=filtered(),name=(o.fileName||'datos')+'-'+new Date().toISOString().slice(0,10);if(!a.length){toast('No hay datos para descargar.','warning');return}const heads=o.cols.map(c=>c.h).concat(o.estado?['Estado']:[]),rowsX=a.map(r=>o.cols.map(c=>xvCell(c,r)).concat(o.estado?[htmlTxt(o.estado(r))]:[]));exportTable(name,b.dataset.x==='csv'?'csv':'xlsx',heads,rowsX,o.fileName||'Datos');toast(a.length+' registros exportados.','success','Descarga lista')}));\n  ");
/* 3) Carga masiva: ejemplo con datos de demostración */
rep("</tr></tbody></table></div></fieldset>'\n +'<fieldset class=\"mk-fieldset\"><legend>Importación Masiva","</tr><tr><td><b>Ejemplo con datos de demostración</b> <span class=\"mk-badge mk-badge--success\" style=\"padding:2px 10px;font-size:11px\">Excel / CSV</span></td><td>Archivo listo para cargar con registros de prueba: al procesarlo todas las filas son válidas.</td><td><div class=\"mk-acts\">'+dl('ejemplo','Descargar ejemplo con datos (Excel)')+dl('ejemplocsv','Descargar ejemplo con datos (CSV)')+'</div></td></tr></tbody></table></div></fieldset>'\n +'<fieldset class=\"mk-fieldset\"><legend>Importación Masiva");
rep("  else{const rows=m.cols.map(c=>'<tr><td>'","  else if(b.dataset.dl==='ejemplo'){download('Ejemplo_'+pre+'_'+base+'.xlsx',buildXlsx(m,m.demo()),XLSX_MIME);toast('Ejemplo con datos de '+m.nombre+' descargado (Excel).','success','Descarga lista')}\n  else if(b.dataset.dl==='ejemplocsv'){download('Ejemplo_'+pre+'_'+base+'.csv',demoCsv(m),'text/csv;charset=utf-8');toast('Ejemplo con datos de '+m.nombre+' descargado (CSV).','success','Descarga lista')}\n  else{const rows=m.cols.map(c=>'<tr><td>'");
/* 4) Nombre comercial de la línea de conexiones */
rep("'<div class=\"mk-apoya\"><span>Apoya a:</span>'","'<div class=\"mk-apoya\"><span'+TIP('Pantallas conectadas con este maestro: las que lo usan y las que se afectan si cambia.')+'>Módulos conectados:</span>'");
rep("margin-top:6px\">Apoya a: '","margin-top:6px\">Módulos conectados: '");
/* 5) Páginas nuevas */
rep("/* --- Carga de archivos --- */",fs.readFileSync('ins_pages.js','utf8')+"\n/* --- Carga de archivos --- */");
rep("/* --- Benchmarks (Crear / Ver / Editar / Inactivar) --- */",fs.readFileSync('ins_pamm.js','utf8')+"\n/* --- Benchmarks (Crear / Ver / Editar / Inactivar) --- */");
/* 6) Evaluación de límites: contraparte en alerta (hilo de la demo) */
rep("Math.abs(l.pct-0.2)<1e-9);let actual","Math.abs(l.pct-0.2)<1e-9),demo2=(l.port===PNAMES[0]&&l.tipo==='CONTRAPARTE'&&l.eval==='MAX'&&Math.abs(l.pct-0.25)<1e-9);let actual");
rep("(demo?0.92:(hash","(demo?0.92:demo2?0.94:(hash");
/* 7) Datos por país */
rep("INSTR_NAMES,ISSUERS};","INSTR_NAMES,ISSUERS,MM_ORDERS,MM_POS,MM_CP,MM_RATES};");
rep("m:[['MINISTERIO DE HACIENDA (TES)','TESORERÍA GENERAL DE LA REPÚBLICA']","m:[['BANCO POPULAR S.A.','BANCO SECURITY'],['BANCO AV VILLAS','BANCO FALABELLA'],['SCOTIABANK COLPATRIA','SCOTIABANK CHILE'],['CORFICOLOMBIANA','BICE INVERSIONES'],['BANCO COOMEVA','BANCO ITAÚ CHILE'],['SIMULTÁNEAS','PACTOS DE RETROCOMPRA'],['SIMULTÁNEA','PACTO DE RETROCOMPRA'],['Simultánea','Pacto de retrocompra'],['TES CORTO','BONO GOBIERNO CORTO'],['IBR OVERNIGHT','TAB OVERNIGHT'],['TASA DE REPO BANREP','TASA DE PACTO BCCH'],['Indicador Bancario de Referencia a 1 día','Tasa Activa Bancaria a 1 día'],['Comisionista','Corredora de bolsa'],['MINISTERIO DE HACIENDA (TES)','TESORERÍA GENERAL DE LA REPÚBLICA']");
rep("m:[['MINISTERIO DE HACIENDA (TES)','MINISTERIO DE HACIENDA (BONOS SOBERANOS)']","m:[['BANCO POPULAR S.A.','BANCO LÓPEZ DE HARO'],['BANCO AV VILLAS','BANCO PROMERICA'],['SCOTIABANK COLPATRIA','SCOTIABANK DOMINICANA'],['CORFICOLOMBIANA','PUESTO DE BOLSA PARALLAX'],['BANCO COOMEVA','BANCO SANTA CRUZ'],['SIMULTÁNEAS','REPORTOS'],['SIMULTÁNEA','REPORTO'],['Simultánea','Reporto'],['TES CORTO','BONO SOBERANO CORTO'],['IBR OVERNIGHT','TASA PASIVA OVERNIGHT'],['TASA DE REPO BANREP','TASA DE REPORTO BCRD'],['Indicador Bancario de Referencia a 1 día','Tasa pasiva promedio a 1 día'],['Comisionista','Puesto de bolsa'],['MINISTERIO DE HACIENDA (TES)','MINISTERIO DE HACIENDA (BONOS SOBERANOS)']");
/* 8) Catálogo de operaciones monetarias */
rep(".concat(DENOMS.map(d=>({t:'Denominador',v:d})))]\n ];",".concat(DENOMS.map(d=>({t:'Denominador',v:d})))],\n  ['Operaciones monetarias',[{h:'Operación',k:'o'},{h:'Descripción',k:'d'},{h:'Plazo típico',k:'p'}],[['CDT','Certificado de depósito a término con un banco','30 a 360 días'],['SIMULTÁNEA','Compra con compromiso de reventa, respaldada en títulos','1 a 30 días'],['INTERBANCARIO','Préstamo de liquidez entre entidades financieras','1 a 7 días'],['OVERNIGHT','Colocación de excedentes a un día','1 día'],['TES CORTO','Título de deuda pública de corto plazo','Hasta 365 días']].map(a=>({o:a[0],d:a[1],p:a[2]}))]\n ];");
rep("CATS[2][2]=CURR[S.pais]","CATS[4][2].forEach(o=>{Object.keys(o).forEach(k=>{o[k]=loc(o[k])})});CATS[2][2]=CURR[S.pais]");
/* 9) Navegación */
rep("['#/parametrizacion/benchmarks','Benchmarks','sliders','pabench','Composición del benchmark de cada portafolio.'],","['#/parametrizacion/benchmarks','Benchmarks','sliders','pabench','Composición del benchmark de cada portafolio.'],['#/parametrizacion/counterparties','Contrapartes y cupos','network','pcp','Entidades de mercado monetario y su cupo autorizado.'],['#/parametrizacion/rates','Tasas de referencia','scale','prates','Tasas de mercado para valorar y comparar el desempeño.'],");
rep("['#/dashboard/sensitivity-measures','Medidas de sensibilidad','network','sens','Analiza duración, convexidad y DV01.']]}","['#/dashboard/sensitivity-measures','Medidas de sensibilidad','network','sens','Analiza duración, convexidad y DV01.'],['#/dashboard/money-market','Mercado monetario','coins','mmpos','Posición, vencimientos y devengo de las operaciones monetarias.']]}");
rep("desc:'Captura y gestión de órdenes de renta fija y renta variable.'","desc:'Captura y gestión de órdenes de renta fija, renta variable y mercado monetario, y su libro de órdenes.'");
rep("['#/orders/variable-income','Renta variable','col','variable','Opera y administra inversiones en acciones.']]}","['#/orders/variable-income','Renta variable','col','variable','Opera y administra inversiones en acciones.'],['#/orders/money-market','Mercado monetario','coins','mm','Opera CDT, simultáneas, interbancarios y overnight con control de cupo.'],['#/orders/reports','Reportes','doc','oreports','Libro de órdenes de todos los mercados, listo para descargar.']]}");
rep("['#/performance-attribution/fixed-income','Atribución renta fija','colinc','pafixed','Curva, spread y selección en renta fija.'],","['#/performance-attribution/fixed-income','Atribución renta fija','colinc','pafixed','Curva, spread y selección en renta fija.'],['#/performance-attribution/money-market','Atribución mercado monetario','coins','pamm','Devengo, plazo, contraparte y liquidez en operaciones monetarias.'],");
rep("Consulta de portafolios, operación de órdenes de inversión, control de límites y análisis de desempeño (Performance attribution).","Consulta de portafolios, operación de órdenes de inversión (renta fija, renta variable y mercado monetario), control de límites y análisis de desempeño (Performance attribution).");
/* 10) Notificaciones */
rep("['ok','Benchmark actualizado'","['warn','Cupo de contraparte al 93%','BANCOLOMBIA S.A. está cerca de su cupo autorizado de $7.200 M en mercado monetario.','Límites','Advertencia','cup-021',1],['info','CDT próximo a vencer','Vence en 12 días un CDT de FIC MONETARIO con BANCOLOMBIA S.A.; revisa el rollover.','Órdenes','Informativo','mm-044',1],['ok','Benchmark actualizado'");
/* 11) Reportes de desempeño: descarga real por reporte */
rep("const st={step:0,port:FUNDS[1],d1:","const st={step:0,port:'Todos',d1:");
rep("selF('w-port','Portafolio',FUNDS,st.port,{req:true})","selF('w-port','Portafolio',['Todos'].concat(FUNDS),st.port,{req:true})");
slice("if(e.target.closest('[data-d]')){const cols=","\n });\n render();","if(e.target.closest('[data-d]')){const ds=reportData(name,st),base=name.replace(/[^\\w]+/g,'-').toLowerCase()+'-'+new Date().toISOString().slice(0,10);exportTable(base,st.fmt==='Excel'?'xlsx':'csv',ds.heads,ds.rows,'Reporte');toast(esc(name),'success','Reporte descargado');m.close()}");
/* 12) Utilidades para pruebas y plantillas */
rep("try{if(localStorage.getItem('mkTheme')==='dark')","window.__mk={MASS,buildXlsx,buildBook,exportTable,readXlsx,parseCSV,demoCsv,zipStore,applyCountry,reportData,mmCalc,cpUsed,bookRows,files:id=>{const m=MASS[id];return {nombre:m.nombre,pre:m.pre||'',head:m.cols.map(c=>c[0]),rows:m.demo(),xlsx:buildXlsx(m,m.demo()),csv:demoCsv(m),estructura:buildXlsx(m)}}};\ntry{if(localStorage.getItem('mkTheme')==='dark')");
fs.writeFileSync('mk.js',s);console.log('mk.js ok',s.length);
